# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWinUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 828)
        self.FrftConfig = QtWidgets.QWidget(MainWindow)
        self.FrftConfig.setAutoFillBackground(False)
        self.FrftConfig.setStyleSheet("background-color: rgb(170, 170, 255)")
        self.FrftConfig.setObjectName("FrftConfig")
        self.tabWidget = QtWidgets.QTabWidget(self.FrftConfig)
        self.tabWidget.setGeometry(QtCore.QRect(40, 10, 1021, 711))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.TX_Config = QtWidgets.QWidget()
        self.TX_Config.setObjectName("TX_Config")
        self.papr_en_obj = QtWidgets.QCheckBox(self.TX_Config)
        self.papr_en_obj.setEnabled(True)
        self.papr_en_obj.setGeometry(QtCore.QRect(41, 31, 96, 22))
        self.papr_en_obj.setObjectName("papr_en_obj")
        self.depapr_thr_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.depapr_thr_obj.setGeometry(QtCore.QRect(41, 81, 83, 22))
        self.depapr_thr_obj.setSpecialValueText("")
        self.depapr_thr_obj.setMaximum(262143)
        self.depapr_thr_obj.setSingleStep(1)
        self.depapr_thr_obj.setProperty("value", 38050)
        self.depapr_thr_obj.setObjectName("depapr_thr_obj")
        self.depapr_thr_label = QtWidgets.QLabel(self.TX_Config)
        self.depapr_thr_label.setGeometry(QtCore.QRect(133, 81, 90, 18))
        self.depapr_thr_label.setObjectName("depapr_thr_label")
        self.depapr_gain_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.depapr_gain_obj.setGeometry(QtCore.QRect(277, 80, 74, 22))
        self.depapr_gain_obj.setSpecialValueText("")
        self.depapr_gain_obj.setMaximum(65535)
        self.depapr_gain_obj.setSingleStep(1)
        self.depapr_gain_obj.setProperty("value", 16384)
        self.depapr_gain_obj.setObjectName("depapr_gain_obj")
        self.depapr_gain_label = QtWidgets.QLabel(self.TX_Config)
        self.depapr_gain_label.setGeometry(QtCore.QRect(360, 80, 99, 18))
        self.depapr_gain_label.setObjectName("depapr_gain_label")
        self.MType_tx_obj = QtWidgets.QComboBox(self.TX_Config)
        self.MType_tx_obj.setGeometry(QtCore.QRect(40, 190, 99, 24))
        self.MType_tx_obj.setEditable(True)
        self.MType_tx_obj.setObjectName("MType_tx_obj")
        self.MType_tx_obj.addItem("")
        self.MType_tx_obj.addItem("")
        self.MType_tx_obj.addItem("")
        self.MType_tx_obj.addItem("")
        self.MType_tx_label = QtWidgets.QLabel(self.TX_Config)
        self.MType_tx_label.setGeometry(QtCore.QRect(150, 190, 81, 18))
        self.MType_tx_label.setObjectName("MType_tx_label")
        self.car_num_tx_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.car_num_tx_obj.setGeometry(QtCore.QRect(40, 240, 71, 25))
        self.car_num_tx_obj.setSpecialValueText("")
        self.car_num_tx_obj.setMaximum(1048575)
        self.car_num_tx_obj.setSingleStep(1)
        self.car_num_tx_obj.setProperty("value", 1048575)
        self.car_num_tx_obj.setDisplayIntegerBase(16)
        self.car_num_tx_obj.setObjectName("car_num_tx_obj")
        self.car_num_tx_label = QtWidgets.QLabel(self.TX_Config)
        self.car_num_tx_label.setGeometry(QtCore.QRect(120, 240, 101, 18))
        self.car_num_tx_label.setObjectName("car_num_tx_label")
        self.Alpha_tx_obj = QtWidgets.QDoubleSpinBox(self.TX_Config)
        self.Alpha_tx_obj.setGeometry(QtCore.QRect(40, 280, 76, 25))
        self.Alpha_tx_obj.setDecimals(1)
        self.Alpha_tx_obj.setMaximum(1.0)
        self.Alpha_tx_obj.setSingleStep(0.1)
        self.Alpha_tx_obj.setProperty("value", 0.5)
        self.Alpha_tx_obj.setObjectName("Alpha_tx_obj")
        self.Alpha_tx_label = QtWidgets.QLabel(self.TX_Config)
        self.Alpha_tx_label.setGeometry(QtCore.QRect(120, 280, 101, 18))
        self.Alpha_tx_label.setObjectName("Alpha_tx_label")
        self.pilot_factor_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.pilot_factor_obj.setGeometry(QtCore.QRect(40, 320, 71, 25))
        self.pilot_factor_obj.setSpecialValueText("")
        self.pilot_factor_obj.setMaximum(65535)
        self.pilot_factor_obj.setSingleStep(1)
        self.pilot_factor_obj.setProperty("value", 32767)
        self.pilot_factor_obj.setObjectName("pilot_factor_obj")
        self.pilot_factor_label = QtWidgets.QLabel(self.TX_Config)
        self.pilot_factor_label.setGeometry(QtCore.QRect(120, 320, 111, 18))
        self.pilot_factor_label.setObjectName("pilot_factor_label")
        self.pss_factor_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.pss_factor_obj.setGeometry(QtCore.QRect(40, 360, 71, 25))
        self.pss_factor_obj.setSpecialValueText("")
        self.pss_factor_obj.setMaximum(65535)
        self.pss_factor_obj.setSingleStep(1)
        self.pss_factor_obj.setProperty("value", 32767)
        self.pss_factor_obj.setObjectName("pss_factor_obj")
        self.pss_factor_label = QtWidgets.QLabel(self.TX_Config)
        self.pss_factor_label.setGeometry(QtCore.QRect(120, 360, 101, 18))
        self.pss_factor_label.setObjectName("pss_factor_label")
        self.Sys_enble_obj = QtWidgets.QCheckBox(self.TX_Config)
        self.Sys_enble_obj.setEnabled(True)
        self.Sys_enble_obj.setGeometry(QtCore.QRect(500, 31, 114, 22))
        self.Sys_enble_obj.setObjectName("Sys_enble_obj")
        self.Sys_reset_obj = QtWidgets.QCheckBox(self.TX_Config)
        self.Sys_reset_obj.setEnabled(True)
        self.Sys_reset_obj.setGeometry(QtCore.QRect(280, 31, 114, 22))
        self.Sys_reset_obj.setObjectName("Sys_reset_obj")
        self.ModeBSorMS_label = QtWidgets.QLabel(self.TX_Config)
        self.ModeBSorMS_label.setGeometry(QtCore.QRect(150, 140, 101, 18))
        self.ModeBSorMS_label.setTextFormat(QtCore.Qt.PlainText)
        self.ModeBSorMS_label.setObjectName("ModeBSorMS_label")
        self.ModeBSorMS_obj = QtWidgets.QComboBox(self.TX_Config)
        self.ModeBSorMS_obj.setGeometry(QtCore.QRect(40, 140, 99, 24))
        self.ModeBSorMS_obj.setEditable(True)
        self.ModeBSorMS_obj.setObjectName("ModeBSorMS_obj")
        self.ModeBSorMS_obj.addItem("")
        self.ModeBSorMS_obj.addItem("")
        self.ModeUDPorPN_label = QtWidgets.QLabel(self.TX_Config)
        self.ModeUDPorPN_label.setGeometry(QtCore.QRect(380, 140, 101, 18))
        self.ModeUDPorPN_label.setTextFormat(QtCore.Qt.PlainText)
        self.ModeUDPorPN_label.setObjectName("ModeUDPorPN_label")
        self.ModeUDPorPN_obj = QtWidgets.QComboBox(self.TX_Config)
        self.ModeUDPorPN_obj.setGeometry(QtCore.QRect(270, 140, 99, 24))
        self.ModeUDPorPN_obj.setEditable(True)
        self.ModeUDPorPN_obj.setObjectName("ModeUDPorPN_obj")
        self.ModeUDPorPN_obj.addItem("")
        self.ModeUDPorPN_obj.addItem("")
        self.Base_loop_en_label = QtWidgets.QLabel(self.TX_Config)
        self.Base_loop_en_label.setGeometry(QtCore.QRect(840, 190, 121, 18))
        self.Base_loop_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.Base_loop_en_label.setObjectName("Base_loop_en_label")
        self.Base_loop_en_obj = QtWidgets.QComboBox(self.TX_Config)
        self.Base_loop_en_obj.setGeometry(QtCore.QRect(710, 190, 121, 24))
        self.Base_loop_en_obj.setEditable(True)
        self.Base_loop_en_obj.setObjectName("Base_loop_en_obj")
        self.Base_loop_en_obj.addItem("")
        self.Base_loop_en_obj.addItem("")
        self.Rx_enb_label = QtWidgets.QLabel(self.TX_Config)
        self.Rx_enb_label.setGeometry(QtCore.QRect(380, 190, 61, 18))
        self.Rx_enb_label.setTextFormat(QtCore.Qt.PlainText)
        self.Rx_enb_label.setObjectName("Rx_enb_label")
        self.Rx_enb_obj = QtWidgets.QComboBox(self.TX_Config)
        self.Rx_enb_obj.setGeometry(QtCore.QRect(270, 190, 99, 24))
        self.Rx_enb_obj.setEditable(True)
        self.Rx_enb_obj.setObjectName("Rx_enb_obj")
        self.Rx_enb_obj.addItem("")
        self.Rx_enb_obj.addItem("")
        self.Rx_channel_obj = QtWidgets.QComboBox(self.TX_Config)
        self.Rx_channel_obj.setGeometry(QtCore.QRect(710, 240, 111, 24))
        self.Rx_channel_obj.setEditable(True)
        self.Rx_channel_obj.setObjectName("Rx_channel_obj")
        self.Rx_channel_obj.addItem("")
        self.Rx_channel_obj.addItem("")
        self.Rx_channel_label = QtWidgets.QLabel(self.TX_Config)
        self.Rx_channel_label.setGeometry(QtCore.QRect(830, 240, 101, 18))
        self.Rx_channel_label.setTextFormat(QtCore.Qt.PlainText)
        self.Rx_channel_label.setObjectName("Rx_channel_label")
        self.Rx_delay_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.Rx_delay_obj.setGeometry(QtCore.QRect(40, 400, 71, 25))
        self.Rx_delay_obj.setSpecialValueText("")
        self.Rx_delay_obj.setMaximum(30)
        self.Rx_delay_obj.setSingleStep(1)
        self.Rx_delay_obj.setProperty("value", 20)
        self.Rx_delay_obj.setObjectName("Rx_delay_obj")
        self.Rx_delay_label = QtWidgets.QLabel(self.TX_Config)
        self.Rx_delay_label.setGeometry(QtCore.QRect(120, 400, 101, 18))
        self.Rx_delay_label.setObjectName("Rx_delay_label")
        self.Time_trig2tx_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.Time_trig2tx_obj.setGeometry(QtCore.QRect(270, 240, 80, 25))
        self.Time_trig2tx_obj.setSpecialValueText("")
        self.Time_trig2tx_obj.setMaximum(16777215)
        self.Time_trig2tx_obj.setSingleStep(1)
        self.Time_trig2tx_obj.setProperty("value", 34000)
        self.Time_trig2tx_obj.setObjectName("Time_trig2tx_obj")
        self.Time_trig2tx_label = QtWidgets.QLabel(self.TX_Config)
        self.Time_trig2tx_label.setGeometry(QtCore.QRect(360, 240, 121, 18))
        self.Time_trig2tx_label.setObjectName("Time_trig2tx_label")
        self.Time_tx_hold_label = QtWidgets.QLabel(self.TX_Config)
        self.Time_tx_hold_label.setGeometry(QtCore.QRect(360, 280, 111, 18))
        self.Time_tx_hold_label.setObjectName("Time_tx_hold_label")
        self.Time_tx_hold_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.Time_tx_hold_obj.setGeometry(QtCore.QRect(270, 280, 80, 25))
        self.Time_tx_hold_obj.setSpecialValueText("")
        self.Time_tx_hold_obj.setMaximum(16777215)
        self.Time_tx_hold_obj.setSingleStep(1)
        self.Time_tx_hold_obj.setProperty("value", 34000)
        self.Time_tx_hold_obj.setObjectName("Time_tx_hold_obj")
        self.ms_T_sync2trig_label = QtWidgets.QLabel(self.TX_Config)
        self.ms_T_sync2trig_label.setGeometry(QtCore.QRect(360, 320, 131, 18))
        self.ms_T_sync2trig_label.setObjectName("ms_T_sync2trig_label")
        self.ms_T_sync2trig_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.ms_T_sync2trig_obj.setGeometry(QtCore.QRect(270, 320, 80, 25))
        self.ms_T_sync2trig_obj.setSpecialValueText("")
        self.ms_T_sync2trig_obj.setMaximum(16777215)
        self.ms_T_sync2trig_obj.setSingleStep(1)
        self.ms_T_sync2trig_obj.setProperty("value", 21880)
        self.ms_T_sync2trig_obj.setObjectName("ms_T_sync2trig_obj")
        self.bs_tdd_time_gap_label = QtWidgets.QLabel(self.TX_Config)
        self.bs_tdd_time_gap_label.setGeometry(QtCore.QRect(360, 360, 101, 18))
        self.bs_tdd_time_gap_label.setObjectName("bs_tdd_time_gap_label")
        self.bs_tdd_time_gap_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.bs_tdd_time_gap_obj.setGeometry(QtCore.QRect(270, 360, 80, 25))
        self.bs_tdd_time_gap_obj.setSpecialValueText("")
        self.bs_tdd_time_gap_obj.setMaximum(16777215)
        self.bs_tdd_time_gap_obj.setSingleStep(1)
        self.bs_tdd_time_gap_obj.setProperty("value", 100000)
        self.bs_tdd_time_gap_obj.setObjectName("bs_tdd_time_gap_obj")
        self.bs_tx_time_gap_label = QtWidgets.QLabel(self.TX_Config)
        self.bs_tx_time_gap_label.setGeometry(QtCore.QRect(360, 400, 131, 18))
        self.bs_tx_time_gap_label.setObjectName("bs_tx_time_gap_label")
        self.bs_tx_time_gap_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.bs_tx_time_gap_obj.setGeometry(QtCore.QRect(270, 400, 80, 25))
        self.bs_tx_time_gap_obj.setSpecialValueText("")
        self.bs_tx_time_gap_obj.setMaximum(16777215)
        self.bs_tx_time_gap_obj.setSingleStep(1)
        self.bs_tx_time_gap_obj.setProperty("value", 50000)
        self.bs_tx_time_gap_obj.setObjectName("bs_tx_time_gap_obj")
        self.Trig_gap_cnt_label = QtWidgets.QLabel(self.TX_Config)
        self.Trig_gap_cnt_label.setGeometry(QtCore.QRect(360, 440, 111, 18))
        self.Trig_gap_cnt_label.setObjectName("Trig_gap_cnt_label")
        self.Trig_gap_cnt_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.Trig_gap_cnt_obj.setGeometry(QtCore.QRect(270, 440, 80, 25))
        self.Trig_gap_cnt_obj.setSpecialValueText("")
        self.Trig_gap_cnt_obj.setMaximum(16777215)
        self.Trig_gap_cnt_obj.setSingleStep(1)
        self.Trig_gap_cnt_obj.setProperty("value", 100000)
        self.Trig_gap_cnt_obj.setObjectName("Trig_gap_cnt_obj")
        self.alway_tx_obj = QtWidgets.QComboBox(self.TX_Config)
        self.alway_tx_obj.setGeometry(QtCore.QRect(500, 190, 99, 24))
        self.alway_tx_obj.setEditable(True)
        self.alway_tx_obj.setObjectName("alway_tx_obj")
        self.alway_tx_obj.addItem("")
        self.alway_tx_obj.addItem("")
        self.alway_tx_label = QtWidgets.QLabel(self.TX_Config)
        self.alway_tx_label.setGeometry(QtCore.QRect(610, 190, 81, 18))
        self.alway_tx_label.setTextFormat(QtCore.Qt.PlainText)
        self.alway_tx_label.setObjectName("alway_tx_label")
        self.tx1_en_obj = QtWidgets.QComboBox(self.TX_Config)
        self.tx1_en_obj.setGeometry(QtCore.QRect(710, 280, 99, 24))
        self.tx1_en_obj.setEditable(True)
        self.tx1_en_obj.setObjectName("tx1_en_obj")
        self.tx1_en_obj.addItem("")
        self.tx1_en_obj.addItem("")
        self.tx1_en_label = QtWidgets.QLabel(self.TX_Config)
        self.tx1_en_label.setGeometry(QtCore.QRect(820, 280, 101, 18))
        self.tx1_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.tx1_en_label.setObjectName("tx1_en_label")
        self.tx2_en_obj = QtWidgets.QComboBox(self.TX_Config)
        self.tx2_en_obj.setGeometry(QtCore.QRect(710, 320, 99, 24))
        self.tx2_en_obj.setEditable(True)
        self.tx2_en_obj.setObjectName("tx2_en_obj")
        self.tx2_en_obj.addItem("")
        self.tx2_en_obj.addItem("")
        self.tx2_en_label = QtWidgets.QLabel(self.TX_Config)
        self.tx2_en_label.setGeometry(QtCore.QRect(820, 320, 101, 18))
        self.tx2_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.tx2_en_label.setObjectName("tx2_en_label")
        self.rx1_en_obj = QtWidgets.QComboBox(self.TX_Config)
        self.rx1_en_obj.setGeometry(QtCore.QRect(710, 360, 99, 24))
        self.rx1_en_obj.setEditable(True)
        self.rx1_en_obj.setObjectName("rx1_en_obj")
        self.rx1_en_obj.addItem("")
        self.rx1_en_obj.addItem("")
        self.rx1_en_label = QtWidgets.QLabel(self.TX_Config)
        self.rx1_en_label.setGeometry(QtCore.QRect(820, 360, 101, 18))
        self.rx1_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.rx1_en_label.setObjectName("rx1_en_label")
        self.rx2_en_obj = QtWidgets.QComboBox(self.TX_Config)
        self.rx2_en_obj.setGeometry(QtCore.QRect(710, 400, 99, 24))
        self.rx2_en_obj.setEditable(True)
        self.rx2_en_obj.setObjectName("rx2_en_obj")
        self.rx2_en_obj.addItem("")
        self.rx2_en_obj.addItem("")
        self.rx2_en_label = QtWidgets.QLabel(self.TX_Config)
        self.rx2_en_label.setGeometry(QtCore.QRect(820, 400, 101, 18))
        self.rx2_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.rx2_en_label.setObjectName("rx2_en_label")
        self.TDD_EN_obj = QtWidgets.QComboBox(self.TX_Config)
        self.TDD_EN_obj.setGeometry(QtCore.QRect(710, 140, 99, 24))
        self.TDD_EN_obj.setEditable(True)
        self.TDD_EN_obj.setObjectName("TDD_EN_obj")
        self.TDD_EN_obj.addItem("")
        self.TDD_EN_obj.addItem("")
        self.TDD_EN_label = QtWidgets.QLabel(self.TX_Config)
        self.TDD_EN_label.setGeometry(QtCore.QRect(820, 140, 101, 18))
        self.TDD_EN_label.setTextFormat(QtCore.Qt.PlainText)
        self.TDD_EN_label.setObjectName("TDD_EN_label")
        self.UDP_loop_label = QtWidgets.QLabel(self.TX_Config)
        self.UDP_loop_label.setGeometry(QtCore.QRect(610, 140, 81, 18))
        self.UDP_loop_label.setTextFormat(QtCore.Qt.PlainText)
        self.UDP_loop_label.setObjectName("UDP_loop_label")
        self.UDP_loop_obj = QtWidgets.QComboBox(self.TX_Config)
        self.UDP_loop_obj.setGeometry(QtCore.QRect(500, 140, 99, 24))
        self.UDP_loop_obj.setEditable(True)
        self.UDP_loop_obj.setObjectName("UDP_loop_obj")
        self.UDP_loop_obj.addItem("")
        self.UDP_loop_obj.addItem("")
        self.BBPort_obj = QtWidgets.QLineEdit(self.TX_Config)
        self.BBPort_obj.setGeometry(QtCore.QRect(290, 610, 71, 41))
        self.BBPort_obj.setObjectName("BBPort_obj")
        self.BBIP_label = QtWidgets.QLabel(self.TX_Config)
        self.BBIP_label.setGeometry(QtCore.QRect(10, 620, 41, 18))
        self.BBIP_label.setTextFormat(QtCore.Qt.PlainText)
        self.BBIP_label.setObjectName("BBIP_label")
        self.BBIP_obj = QtWidgets.QLineEdit(self.TX_Config)
        self.BBIP_obj.setGeometry(QtCore.QRect(60, 610, 121, 41))
        self.BBIP_obj.setObjectName("BBIP_obj")
        self.BBPort_label = QtWidgets.QLabel(self.TX_Config)
        self.BBPort_label.setGeometry(QtCore.QRect(230, 620, 61, 18))
        self.BBPort_label.setTextFormat(QtCore.Qt.PlainText)
        self.BBPort_label.setObjectName("BBPort_label")
        self.tabWidget.addTab(self.TX_Config, "")
        self.RX_Config = QtWidgets.QWidget()
        self.RX_Config.setObjectName("RX_Config")
        self.MType_rx_label = QtWidgets.QLabel(self.RX_Config)
        self.MType_rx_label.setGeometry(QtCore.QRect(130, 30, 80, 18))
        self.MType_rx_label.setObjectName("MType_rx_label")
        self.MType_rx_obj = QtWidgets.QComboBox(self.RX_Config)
        self.MType_rx_obj.setGeometry(QtCore.QRect(20, 30, 99, 24))
        self.MType_rx_obj.setEditable(True)
        self.MType_rx_obj.setObjectName("MType_rx_obj")
        self.MType_rx_obj.addItem("")
        self.MType_rx_obj.addItem("")
        self.MType_rx_obj.addItem("")
        self.MType_rx_obj.addItem("")
        self.agc_en_label = QtWidgets.QLabel(self.RX_Config)
        self.agc_en_label.setGeometry(QtCore.QRect(130, 70, 61, 18))
        self.agc_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.agc_en_label.setObjectName("agc_en_label")
        self.agc_en_obj = QtWidgets.QComboBox(self.RX_Config)
        self.agc_en_obj.setGeometry(QtCore.QRect(20, 70, 99, 24))
        self.agc_en_obj.setEditable(True)
        self.agc_en_obj.setObjectName("agc_en_obj")
        self.agc_en_obj.addItem("")
        self.agc_en_obj.addItem("")
        self.frft_en_label = QtWidgets.QLabel(self.RX_Config)
        self.frft_en_label.setGeometry(QtCore.QRect(130, 110, 61, 18))
        self.frft_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.frft_en_label.setObjectName("frft_en_label")
        self.frft_en_obj = QtWidgets.QComboBox(self.RX_Config)
        self.frft_en_obj.setGeometry(QtCore.QRect(20, 110, 99, 24))
        self.frft_en_obj.setEditable(True)
        self.frft_en_obj.setObjectName("frft_en_obj")
        self.frft_en_obj.addItem("")
        self.frft_en_obj.addItem("")
        self.car_num_rx_label = QtWidgets.QLabel(self.RX_Config)
        self.car_num_rx_label.setGeometry(QtCore.QRect(130, 150, 101, 18))
        self.car_num_rx_label.setObjectName("car_num_rx_label")
        self.car_num_rx_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.car_num_rx_obj.setGeometry(QtCore.QRect(20, 150, 99, 24))
        self.car_num_rx_obj.setSpecialValueText("")
        self.car_num_rx_obj.setMaximum(1048575)
        self.car_num_rx_obj.setSingleStep(1)
        self.car_num_rx_obj.setProperty("value", 1048575)
        self.car_num_rx_obj.setDisplayIntegerBase(16)
        self.car_num_rx_obj.setObjectName("car_num_rx_obj")
        self.i_freq_est_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.i_freq_est_obj.setGeometry(QtCore.QRect(20, 190, 99, 24))
        self.i_freq_est_obj.setMaximum(1000)
        self.i_freq_est_obj.setObjectName("i_freq_est_obj")
        self.i_freq_est_label = QtWidgets.QLabel(self.RX_Config)
        self.i_freq_est_label.setGeometry(QtCore.QRect(130, 190, 101, 18))
        self.i_freq_est_label.setObjectName("i_freq_est_label")
        self.sync_factor_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.sync_factor_obj.setGeometry(QtCore.QRect(20, 230, 99, 24))
        self.sync_factor_obj.setMaximum(65535)
        self.sync_factor_obj.setProperty("value", 20384)
        self.sync_factor_obj.setObjectName("sync_factor_obj")
        self.sync_factor_label = QtWidgets.QLabel(self.RX_Config)
        self.sync_factor_label.setGeometry(QtCore.QRect(130, 230, 101, 18))
        self.sync_factor_label.setObjectName("sync_factor_label")
        self.equa_factor_label = QtWidgets.QLabel(self.RX_Config)
        self.equa_factor_label.setGeometry(QtCore.QRect(130, 270, 101, 18))
        self.equa_factor_label.setObjectName("equa_factor_label")
        self.equa_factor_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.equa_factor_obj.setGeometry(QtCore.QRect(20, 270, 99, 24))
        self.equa_factor_obj.setMaximum(65535)
        self.equa_factor_obj.setProperty("value", 4022)
        self.equa_factor_obj.setObjectName("equa_factor_obj")
        self.Alpha_rx_obj = QtWidgets.QDoubleSpinBox(self.RX_Config)
        self.Alpha_rx_obj.setGeometry(QtCore.QRect(20, 310, 99, 24))
        self.Alpha_rx_obj.setDecimals(1)
        self.Alpha_rx_obj.setMaximum(1.0)
        self.Alpha_rx_obj.setSingleStep(0.1)
        self.Alpha_rx_obj.setProperty("value", 0.5)
        self.Alpha_rx_obj.setObjectName("Alpha_rx_obj")
        self.Alpha_rx_label = QtWidgets.QLabel(self.RX_Config)
        self.Alpha_rx_label.setGeometry(QtCore.QRect(130, 310, 101, 18))
        self.Alpha_rx_label.setObjectName("Alpha_rx_label")
        self.equa_amp_en_label = QtWidgets.QLabel(self.RX_Config)
        self.equa_amp_en_label.setGeometry(QtCore.QRect(130, 400, 101, 18))
        self.equa_amp_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.equa_amp_en_label.setObjectName("equa_amp_en_label")
        self.equa_amp_en_obj = QtWidgets.QComboBox(self.RX_Config)
        self.equa_amp_en_obj.setGeometry(QtCore.QRect(20, 400, 99, 24))
        self.equa_amp_en_obj.setEditable(True)
        self.equa_amp_en_obj.setObjectName("equa_amp_en_obj")
        self.equa_amp_en_obj.addItem("")
        self.equa_amp_en_obj.addItem("")
        self.car_thr1_label = QtWidgets.QLabel(self.RX_Config)
        self.car_thr1_label.setGeometry(QtCore.QRect(130, 440, 101, 18))
        self.car_thr1_label.setObjectName("car_thr1_label")
        self.car_thr1_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.car_thr1_obj.setGeometry(QtCore.QRect(20, 440, 99, 24))
        self.car_thr1_obj.setMaximum(2147483647)
        self.car_thr1_obj.setProperty("value", 102656)
        self.car_thr1_obj.setDisplayIntegerBase(10)
        self.car_thr1_obj.setObjectName("car_thr1_obj")
        self.mmse_thr_label = QtWidgets.QLabel(self.RX_Config)
        self.mmse_thr_label.setGeometry(QtCore.QRect(130, 560, 101, 18))
        self.mmse_thr_label.setObjectName("mmse_thr_label")
        self.mmse_thr_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.mmse_thr_obj.setGeometry(QtCore.QRect(20, 560, 99, 24))
        self.mmse_thr_obj.setMaximum(2147483647)
        self.mmse_thr_obj.setProperty("value", 1000)
        self.mmse_thr_obj.setObjectName("mmse_thr_obj")
        self.car_thr3_label = QtWidgets.QLabel(self.RX_Config)
        self.car_thr3_label.setGeometry(QtCore.QRect(130, 520, 101, 18))
        self.car_thr3_label.setObjectName("car_thr3_label")
        self.car_thr3_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.car_thr3_obj.setGeometry(QtCore.QRect(20, 520, 99, 24))
        self.car_thr3_obj.setMaximum(2147483647)
        self.car_thr3_obj.setProperty("value", 625000000)
        self.car_thr3_obj.setObjectName("car_thr3_obj")
        self.car_thr2_label = QtWidgets.QLabel(self.RX_Config)
        self.car_thr2_label.setGeometry(QtCore.QRect(130, 480, 101, 18))
        self.car_thr2_label.setObjectName("car_thr2_label")
        self.car_thr2_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.car_thr2_obj.setGeometry(QtCore.QRect(20, 480, 99, 24))
        self.car_thr2_obj.setMaximum(2147483647)
        self.car_thr2_obj.setProperty("value", 6250000)
        self.car_thr2_obj.setObjectName("car_thr2_obj")
        self.equa_amp_label = QtWidgets.QLabel(self.RX_Config)
        self.equa_amp_label.setGeometry(QtCore.QRect(130, 360, 101, 18))
        self.equa_amp_label.setObjectName("equa_amp_label")
        self.equa_amp_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.equa_amp_obj.setGeometry(QtCore.QRect(20, 360, 99, 24))
        self.equa_amp_obj.setMaximum(65535)
        self.equa_amp_obj.setProperty("value", 16384)
        self.equa_amp_obj.setObjectName("equa_amp_obj")
        self.tabWidget.addTab(self.RX_Config, "")
        self.RF_Config = QtWidgets.QWidget()
        self.RF_Config.setObjectName("RF_Config")
        self.Amplifier_label = QtWidgets.QLabel(self.RF_Config)
        self.Amplifier_label.setGeometry(QtCore.QRect(130, 30, 81, 18))
        self.Amplifier_label.setTextFormat(QtCore.Qt.PlainText)
        self.Amplifier_label.setObjectName("Amplifier_label")
        self.Amplifier_obj = QtWidgets.QComboBox(self.RF_Config)
        self.Amplifier_obj.setGeometry(QtCore.QRect(20, 30, 99, 24))
        self.Amplifier_obj.setEditable(True)
        self.Amplifier_obj.setObjectName("Amplifier_obj")
        self.Amplifier_obj.addItem("")
        self.Amplifier_obj.addItem("")
        self.filter3_3p5G_obj = QtWidgets.QComboBox(self.RF_Config)
        self.filter3_3p5G_obj.setGeometry(QtCore.QRect(20, 80, 99, 24))
        self.filter3_3p5G_obj.setEditable(True)
        self.filter3_3p5G_obj.setObjectName("filter3_3p5G_obj")
        self.filter3_3p5G_obj.addItem("")
        self.filter3_3p5G_obj.addItem("")
        self.filter3_3p5G_label = QtWidgets.QLabel(self.RF_Config)
        self.filter3_3p5G_label.setGeometry(QtCore.QRect(130, 80, 121, 18))
        self.filter3_3p5G_label.setTextFormat(QtCore.Qt.PlainText)
        self.filter3_3p5G_label.setObjectName("filter3_3p5G_label")
        self.filter3p5_4G_obj = QtWidgets.QComboBox(self.RF_Config)
        self.filter3p5_4G_obj.setGeometry(QtCore.QRect(20, 130, 99, 24))
        self.filter3p5_4G_obj.setEditable(True)
        self.filter3p5_4G_obj.setObjectName("filter3p5_4G_obj")
        self.filter3p5_4G_obj.addItem("")
        self.filter3p5_4G_obj.addItem("")
        self.filter3p5_4G_label = QtWidgets.QLabel(self.RF_Config)
        self.filter3p5_4G_label.setGeometry(QtCore.QRect(130, 130, 111, 18))
        self.filter3p5_4G_label.setTextFormat(QtCore.Qt.PlainText)
        self.filter3p5_4G_label.setObjectName("filter3p5_4G_label")
        self.filter4p5_5G_obj = QtWidgets.QComboBox(self.RF_Config)
        self.filter4p5_5G_obj.setGeometry(QtCore.QRect(20, 180, 99, 24))
        self.filter4p5_5G_obj.setEditable(True)
        self.filter4p5_5G_obj.setObjectName("filter4p5_5G_obj")
        self.filter4p5_5G_obj.addItem("")
        self.filter4p5_5G_obj.addItem("")
        self.filter4p5_5G_label = QtWidgets.QLabel(self.RF_Config)
        self.filter4p5_5G_label.setGeometry(QtCore.QRect(130, 180, 111, 18))
        self.filter4p5_5G_label.setTextFormat(QtCore.Qt.PlainText)
        self.filter4p5_5G_label.setObjectName("filter4p5_5G_label")
        self.filter5_5p5G_obj = QtWidgets.QComboBox(self.RF_Config)
        self.filter5_5p5G_obj.setGeometry(QtCore.QRect(20, 230, 99, 24))
        self.filter5_5p5G_obj.setEditable(True)
        self.filter5_5p5G_obj.setObjectName("filter5_5p5G_obj")
        self.filter5_5p5G_obj.addItem("")
        self.filter5_5p5G_obj.addItem("")
        self.filter5_5p5G_label = QtWidgets.QLabel(self.RF_Config)
        self.filter5_5p5G_label.setGeometry(QtCore.QRect(130, 230, 111, 18))
        self.filter5_5p5G_label.setTextFormat(QtCore.Qt.PlainText)
        self.filter5_5p5G_label.setObjectName("filter5_5p5G_label")
        self.RFIP_obj = QtWidgets.QLineEdit(self.RF_Config)
        self.RFIP_obj.setGeometry(QtCore.QRect(60, 610, 121, 41))
        self.RFIP_obj.setObjectName("RFIP_obj")
        self.RFIP_label = QtWidgets.QLabel(self.RF_Config)
        self.RFIP_label.setGeometry(QtCore.QRect(10, 620, 41, 18))
        self.RFIP_label.setTextFormat(QtCore.Qt.PlainText)
        self.RFIP_label.setObjectName("RFIP_label")
        self.RFPort_label = QtWidgets.QLabel(self.RF_Config)
        self.RFPort_label.setGeometry(QtCore.QRect(230, 620, 61, 18))
        self.RFPort_label.setTextFormat(QtCore.Qt.PlainText)
        self.RFPort_label.setObjectName("RFPort_label")
        self.RFPort_obj = QtWidgets.QLineEdit(self.RF_Config)
        self.RFPort_obj.setGeometry(QtCore.QRect(290, 610, 71, 41))
        self.RFPort_obj.setObjectName("RFPort_obj")
        self.tabWidget.addTab(self.RF_Config, "")
        self.statistical = QtWidgets.QWidget()
        self.statistical.setObjectName("statistical")
        self.start = QtWidgets.QPushButton(self.statistical)
        self.start.setGeometry(QtCore.QRect(250, 540, 112, 34))
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.statistical)
        self.stop.setGeometry(QtCore.QRect(380, 540, 112, 34))
        self.stop.setObjectName("stop")
        self.noise_pwr_sum_label = QtWidgets.QLabel(self.statistical)
        self.noise_pwr_sum_label.setGeometry(QtCore.QRect(600, 40, 131, 18))
        self.noise_pwr_sum_label.setObjectName("noise_pwr_sum_label")
        self.noise_pwr_sum_show = QtWidgets.QLabel(self.statistical)
        self.noise_pwr_sum_show.setGeometry(QtCore.QRect(730, 40, 81, 18))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.noise_pwr_sum_show.setFont(font)
        self.noise_pwr_sum_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noise_pwr_sum_show.setText("")
        self.noise_pwr_sum_show.setObjectName("noise_pwr_sum_show")
        self.singal_pwr_sum_show = QtWidgets.QLabel(self.statistical)
        self.singal_pwr_sum_show.setGeometry(QtCore.QRect(480, 40, 81, 18))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.singal_pwr_sum_show.setFont(font)
        self.singal_pwr_sum_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.singal_pwr_sum_show.setText("")
        self.singal_pwr_sum_show.setObjectName("singal_pwr_sum_show")
        self.singal_pwr_sum_label = QtWidgets.QLabel(self.statistical)
        self.singal_pwr_sum_label.setGeometry(QtCore.QRect(340, 40, 131, 18))
        self.singal_pwr_sum_label.setObjectName("singal_pwr_sum_label")
        self.SNR_show = QtWidgets.QLabel(self.statistical)
        self.SNR_show.setGeometry(QtCore.QRect(340, 70, 471, 301))
        self.SNR_show.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.SNR_show.setText("")
        self.SNR_show.setObjectName("SNR_show")
        self.layoutWidget = QtWidgets.QWidget(self.statistical)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 51, 191, 338))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.errbit_show = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.errbit_show.setFont(font)
        self.errbit_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.errbit_show.setText("")
        self.errbit_show.setTextFormat(QtCore.Qt.AutoText)
        self.errbit_show.setObjectName("errbit_show")
        self.gridLayout.addWidget(self.errbit_show, 0, 1, 1, 1)
        self.tolfrm_show = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tolfrm_show.setFont(font)
        self.tolfrm_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tolfrm_show.setText("")
        self.tolfrm_show.setObjectName("tolfrm_show")
        self.gridLayout.addWidget(self.tolfrm_show, 1, 1, 1, 1)
        self.o_freq_est_t_label = QtWidgets.QLabel(self.layoutWidget)
        self.o_freq_est_t_label.setObjectName("o_freq_est_t_label")
        self.gridLayout.addWidget(self.o_freq_est_t_label, 8, 0, 1, 2)
        self.hard_decision_err_label = QtWidgets.QLabel(self.layoutWidget)
        self.hard_decision_err_label.setObjectName("hard_decision_err_label")
        self.gridLayout.addWidget(self.hard_decision_err_label, 4, 0, 1, 2)
        self.hard_decision_err_show = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.hard_decision_err_show.setFont(font)
        self.hard_decision_err_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.hard_decision_err_show.setText("")
        self.hard_decision_err_show.setObjectName("hard_decision_err_show")
        self.gridLayout.addWidget(self.hard_decision_err_show, 5, 1, 1, 1)
        self.crc_error_show = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.crc_error_show.setFont(font)
        self.crc_error_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.crc_error_show.setText("")
        self.crc_error_show.setObjectName("crc_error_show")
        self.gridLayout.addWidget(self.crc_error_show, 11, 1, 1, 1)
        self.errbit_label = QtWidgets.QLabel(self.layoutWidget)
        self.errbit_label.setObjectName("errbit_label")
        self.gridLayout.addWidget(self.errbit_label, 0, 0, 1, 1)
        self.tolfrm_label = QtWidgets.QLabel(self.layoutWidget)
        self.tolfrm_label.setObjectName("tolfrm_label")
        self.gridLayout.addWidget(self.tolfrm_label, 1, 0, 1, 1)
        self.o_freq_est_r_label = QtWidgets.QLabel(self.layoutWidget)
        self.o_freq_est_r_label.setObjectName("o_freq_est_r_label")
        self.gridLayout.addWidget(self.o_freq_est_r_label, 6, 0, 1, 2)
        self.o_freq_est_r_show = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.o_freq_est_r_show.setFont(font)
        self.o_freq_est_r_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.o_freq_est_r_show.setText("")
        self.o_freq_est_r_show.setObjectName("o_freq_est_r_show")
        self.gridLayout.addWidget(self.o_freq_est_r_show, 7, 1, 1, 1)
        self.o_freq_est_t_show = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.o_freq_est_t_show.setFont(font)
        self.o_freq_est_t_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.o_freq_est_t_show.setText("")
        self.o_freq_est_t_show.setObjectName("o_freq_est_t_show")
        self.gridLayout.addWidget(self.o_freq_est_t_show, 9, 1, 1, 1)
        self.crc_error_label = QtWidgets.QLabel(self.layoutWidget)
        self.crc_error_label.setObjectName("crc_error_label")
        self.gridLayout.addWidget(self.crc_error_label, 10, 0, 1, 2)
        self.error_dft_label = QtWidgets.QLabel(self.layoutWidget)
        self.error_dft_label.setObjectName("error_dft_label")
        self.gridLayout.addWidget(self.error_dft_label, 2, 0, 1, 2)
        self.error_dft_show = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.error_dft_show.setFont(font)
        self.error_dft_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.error_dft_show.setText("")
        self.error_dft_show.setObjectName("error_dft_show")
        self.gridLayout.addWidget(self.error_dft_show, 3, 1, 1, 1)
        self.statisticalPort_label = QtWidgets.QLabel(self.statistical)
        self.statisticalPort_label.setGeometry(QtCore.QRect(10, 550, 141, 18))
        self.statisticalPort_label.setTextFormat(QtCore.Qt.PlainText)
        self.statisticalPort_label.setObjectName("statisticalPort_label")
        self.statisticalPort_obj = QtWidgets.QLineEdit(self.statistical)
        self.statisticalPort_obj.setGeometry(QtCore.QRect(160, 540, 71, 34))
        self.statisticalPort_obj.setObjectName("statisticalPort_obj")
        self.tabWidget.addTab(self.statistical, "")
        self.setDefault = QtWidgets.QPushButton(self.FrftConfig)
        self.setDefault.setGeometry(QtCore.QRect(60, 730, 112, 34))
        self.setDefault.setObjectName("setDefault")
        self.sendConfig = QtWidgets.QPushButton(self.FrftConfig)
        self.sendConfig.setGeometry(QtCore.QRect(220, 730, 112, 34))
        self.sendConfig.setObjectName("sendConfig")
        self.sendData = QtWidgets.QPushButton(self.FrftConfig)
        self.sendData.setGeometry(QtCore.QRect(380, 730, 112, 34))
        self.sendData.setObjectName("sendData")
        self.stopData = QtWidgets.QPushButton(self.FrftConfig)
        self.stopData.setGeometry(QtCore.QRect(540, 730, 112, 34))
        self.stopData.setObjectName("stopData")
        MainWindow.setCentralWidget(self.FrftConfig)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.MType_tx_obj.setCurrentIndex(0)
        self.ModeBSorMS_obj.setCurrentIndex(0)
        self.ModeUDPorPN_obj.setCurrentIndex(0)
        self.Base_loop_en_obj.setCurrentIndex(0)
        self.Rx_enb_obj.setCurrentIndex(0)
        self.Rx_channel_obj.setCurrentIndex(0)
        self.alway_tx_obj.setCurrentIndex(0)
        self.tx1_en_obj.setCurrentIndex(0)
        self.tx2_en_obj.setCurrentIndex(0)
        self.rx1_en_obj.setCurrentIndex(0)
        self.rx2_en_obj.setCurrentIndex(0)
        self.TDD_EN_obj.setCurrentIndex(0)
        self.UDP_loop_obj.setCurrentIndex(0)
        self.MType_rx_obj.setCurrentIndex(0)
        self.agc_en_obj.setCurrentIndex(0)
        self.frft_en_obj.setCurrentIndex(0)
        self.equa_amp_en_obj.setCurrentIndex(1)
        self.Amplifier_obj.setCurrentIndex(0)
        self.filter3_3p5G_obj.setCurrentIndex(0)
        self.filter3p5_4G_obj.setCurrentIndex(0)
        self.filter4p5_5G_obj.setCurrentIndex(0)
        self.filter5_5p5G_obj.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.papr_en_obj.setText(_translate("MainWindow", "papr_en"))
        self.depapr_thr_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.depapr_thr_label.setText(_translate("MainWindow", "depapr_thr"))
        self.depapr_gain_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.depapr_gain_label.setText(_translate("MainWindow", "depapr_gain"))
        self.MType_tx_obj.setCurrentText(_translate("MainWindow", "QPSK"))
        self.MType_tx_obj.setItemText(0, _translate("MainWindow", "QPSK"))
        self.MType_tx_obj.setItemText(1, _translate("MainWindow", "16QAM"))
        self.MType_tx_obj.setItemText(2, _translate("MainWindow", "64QAM"))
        self.MType_tx_obj.setItemText(3, _translate("MainWindow", "256QAM"))
        self.MType_tx_label.setText(_translate("MainWindow", "MTpye_tx"))
        self.car_num_tx_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.car_num_tx_label.setText(_translate("MainWindow", "car_num_tx"))
        self.Alpha_tx_label.setText(_translate("MainWindow", "Alpha_tx"))
        self.pilot_factor_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.pilot_factor_label.setText(_translate("MainWindow", "pilot_factor"))
        self.pss_factor_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.pss_factor_label.setText(_translate("MainWindow", "pss_factor"))
        self.Sys_enble_obj.setText(_translate("MainWindow", "Sys_enble"))
        self.Sys_reset_obj.setText(_translate("MainWindow", "Sys_reset"))
        self.ModeBSorMS_label.setText(_translate("MainWindow", "ModeBSorMS"))
        self.ModeBSorMS_obj.setCurrentText(_translate("MainWindow", "MS"))
        self.ModeBSorMS_obj.setItemText(0, _translate("MainWindow", "MS"))
        self.ModeBSorMS_obj.setItemText(1, _translate("MainWindow", "BS"))
        self.ModeUDPorPN_label.setText(_translate("MainWindow", "ModeUDPorPN"))
        self.ModeUDPorPN_obj.setCurrentText(_translate("MainWindow", "UDP"))
        self.ModeUDPorPN_obj.setItemText(0, _translate("MainWindow", "UDP"))
        self.ModeUDPorPN_obj.setItemText(1, _translate("MainWindow", "PN"))
        self.Base_loop_en_label.setText(_translate("MainWindow", "Base_loop_en"))
        self.Base_loop_en_obj.setCurrentText(_translate("MainWindow", "outterLoop"))
        self.Base_loop_en_obj.setItemText(0, _translate("MainWindow", "outterLoop"))
        self.Base_loop_en_obj.setItemText(1, _translate("MainWindow", "innerLoop"))
        self.Rx_enb_label.setText(_translate("MainWindow", "Rx_enb"))
        self.Rx_enb_obj.setCurrentText(_translate("MainWindow", "normal"))
        self.Rx_enb_obj.setItemText(0, _translate("MainWindow", "normal"))
        self.Rx_enb_obj.setItemText(1, _translate("MainWindow", "debug"))
        self.Rx_channel_obj.setCurrentText(_translate("MainWindow", "channel 0"))
        self.Rx_channel_obj.setItemText(0, _translate("MainWindow", "channel 0"))
        self.Rx_channel_obj.setItemText(1, _translate("MainWindow", "channel 1"))
        self.Rx_channel_label.setText(_translate("MainWindow", "Rx_channel"))
        self.Rx_delay_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.Rx_delay_label.setText(_translate("MainWindow", "Rx_delay"))
        self.Time_trig2tx_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.Time_trig2tx_label.setText(_translate("MainWindow", "Time_trig2tx"))
        self.Time_tx_hold_label.setText(_translate("MainWindow", "Time_tx_hold"))
        self.Time_tx_hold_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.ms_T_sync2trig_label.setText(_translate("MainWindow", "ms_T_sync2trig"))
        self.ms_T_sync2trig_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.bs_tdd_time_gap_label.setText(_translate("MainWindow", "bs_tdd_time_gap"))
        self.bs_tdd_time_gap_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.bs_tx_time_gap_label.setText(_translate("MainWindow", "bs_tx_time_gap"))
        self.bs_tx_time_gap_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.Trig_gap_cnt_label.setText(_translate("MainWindow", "Trig_gap_cnt"))
        self.Trig_gap_cnt_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.alway_tx_obj.setCurrentText(_translate("MainWindow", "TXandRX"))
        self.alway_tx_obj.setItemText(0, _translate("MainWindow", "TXandRX"))
        self.alway_tx_obj.setItemText(1, _translate("MainWindow", "onlyTX"))
        self.alway_tx_label.setText(_translate("MainWindow", "alway_tx"))
        self.tx1_en_obj.setCurrentText(_translate("MainWindow", "close"))
        self.tx1_en_obj.setItemText(0, _translate("MainWindow", "close"))
        self.tx1_en_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.tx1_en_label.setText(_translate("MainWindow", "tx1_en"))
        self.tx2_en_obj.setCurrentText(_translate("MainWindow", "close"))
        self.tx2_en_obj.setItemText(0, _translate("MainWindow", "close"))
        self.tx2_en_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.tx2_en_label.setText(_translate("MainWindow", "tx2_en"))
        self.rx1_en_obj.setCurrentText(_translate("MainWindow", "close"))
        self.rx1_en_obj.setItemText(0, _translate("MainWindow", "close"))
        self.rx1_en_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.rx1_en_label.setText(_translate("MainWindow", "rx1_en"))
        self.rx2_en_obj.setCurrentText(_translate("MainWindow", "close"))
        self.rx2_en_obj.setItemText(0, _translate("MainWindow", "close"))
        self.rx2_en_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.rx2_en_label.setText(_translate("MainWindow", "rx2_en"))
        self.TDD_EN_obj.setCurrentText(_translate("MainWindow", "close"))
        self.TDD_EN_obj.setItemText(0, _translate("MainWindow", "close"))
        self.TDD_EN_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.TDD_EN_label.setText(_translate("MainWindow", "TDD_EN"))
        self.UDP_loop_label.setText(_translate("MainWindow", "UDP_loop"))
        self.UDP_loop_obj.setCurrentText(_translate("MainWindow", "close"))
        self.UDP_loop_obj.setItemText(0, _translate("MainWindow", "close"))
        self.UDP_loop_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.BBPort_obj.setText(_translate("MainWindow", "8000"))
        self.BBIP_label.setText(_translate("MainWindow", "BBIP"))
        self.BBIP_obj.setText(_translate("MainWindow", "192.168.1.84"))
        self.BBPort_label.setText(_translate("MainWindow", "BBPort"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TX_Config), _translate("MainWindow", "TX_Config"))
        self.MType_rx_label.setText(_translate("MainWindow", "MType_rx"))
        self.MType_rx_obj.setCurrentText(_translate("MainWindow", "QPSK"))
        self.MType_rx_obj.setItemText(0, _translate("MainWindow", "QPSK"))
        self.MType_rx_obj.setItemText(1, _translate("MainWindow", "16QAM"))
        self.MType_rx_obj.setItemText(2, _translate("MainWindow", "64QAM"))
        self.MType_rx_obj.setItemText(3, _translate("MainWindow", "256QAM"))
        self.agc_en_label.setText(_translate("MainWindow", "agc_en"))
        self.agc_en_obj.setCurrentText(_translate("MainWindow", "close"))
        self.agc_en_obj.setItemText(0, _translate("MainWindow", "close"))
        self.agc_en_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.frft_en_label.setText(_translate("MainWindow", "frft_en"))
        self.frft_en_obj.setCurrentText(_translate("MainWindow", "close"))
        self.frft_en_obj.setItemText(0, _translate("MainWindow", "close"))
        self.frft_en_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.car_num_rx_label.setText(_translate("MainWindow", "car_num_rx"))
        self.car_num_rx_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.i_freq_est_obj.setSuffix(_translate("MainWindow", "Hz"))
        self.i_freq_est_label.setText(_translate("MainWindow", "i_freq_est"))
        self.sync_factor_label.setText(_translate("MainWindow", "sync_factor"))
        self.equa_factor_label.setText(_translate("MainWindow", "equa_factor"))
        self.Alpha_rx_label.setText(_translate("MainWindow", "Alpha_rx"))
        self.equa_amp_en_label.setText(_translate("MainWindow", "equa_amp_en"))
        self.equa_amp_en_obj.setCurrentText(_translate("MainWindow", "enable"))
        self.equa_amp_en_obj.setItemText(0, _translate("MainWindow", "close"))
        self.equa_amp_en_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.car_thr1_label.setText(_translate("MainWindow", "car_thr1"))
        self.mmse_thr_label.setText(_translate("MainWindow", "mmse_thr"))
        self.car_thr3_label.setText(_translate("MainWindow", "car_thr3"))
        self.car_thr2_label.setText(_translate("MainWindow", "car_thr2"))
        self.equa_amp_label.setText(_translate("MainWindow", "equa_amp"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RX_Config), _translate("MainWindow", "RX_Config"))
        self.Amplifier_label.setText(_translate("MainWindow", "Amplifier"))
        self.Amplifier_obj.setCurrentText(_translate("MainWindow", "close"))
        self.Amplifier_obj.setItemText(0, _translate("MainWindow", "close"))
        self.Amplifier_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.filter3_3p5G_obj.setCurrentText(_translate("MainWindow", "close"))
        self.filter3_3p5G_obj.setItemText(0, _translate("MainWindow", "close"))
        self.filter3_3p5G_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.filter3_3p5G_label.setText(_translate("MainWindow", "filter3_3p5G"))
        self.filter3p5_4G_obj.setCurrentText(_translate("MainWindow", "close"))
        self.filter3p5_4G_obj.setItemText(0, _translate("MainWindow", "close"))
        self.filter3p5_4G_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.filter3p5_4G_label.setText(_translate("MainWindow", "filter3p5_4G"))
        self.filter4p5_5G_obj.setCurrentText(_translate("MainWindow", "close"))
        self.filter4p5_5G_obj.setItemText(0, _translate("MainWindow", "close"))
        self.filter4p5_5G_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.filter4p5_5G_label.setText(_translate("MainWindow", "filter4p5_5G"))
        self.filter5_5p5G_obj.setCurrentText(_translate("MainWindow", "close"))
        self.filter5_5p5G_obj.setItemText(0, _translate("MainWindow", "close"))
        self.filter5_5p5G_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.filter5_5p5G_label.setText(_translate("MainWindow", "filter5_5p5G"))
        self.RFIP_obj.setText(_translate("MainWindow", "192.168.1.38"))
        self.RFIP_label.setText(_translate("MainWindow", "RFIP"))
        self.RFPort_label.setText(_translate("MainWindow", "RFPort"))
        self.RFPort_obj.setText(_translate("MainWindow", "6005"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RF_Config), _translate("MainWindow", "RF_Config"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.noise_pwr_sum_label.setText(_translate("MainWindow", "noise_pwr_sum"))
        self.singal_pwr_sum_label.setText(_translate("MainWindow", "singal_pwr_sum"))
        self.o_freq_est_t_label.setText(_translate("MainWindow", "o_freq_est_t"))
        self.hard_decision_err_label.setText(_translate("MainWindow", "hard_decision_err"))
        self.errbit_label.setText(_translate("MainWindow", "errbit"))
        self.tolfrm_label.setText(_translate("MainWindow", "tolfrm"))
        self.o_freq_est_r_label.setText(_translate("MainWindow", "o_freq_est_r"))
        self.crc_error_label.setText(_translate("MainWindow", "crc_error"))
        self.error_dft_label.setText(_translate("MainWindow", "error_dft"))
        self.statisticalPort_label.setText(_translate("MainWindow", "statisticalPort"))
        self.statisticalPort_obj.setText(_translate("MainWindow", "7000"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statistical), _translate("MainWindow", "Statistical"))
        self.setDefault.setText(_translate("MainWindow", "setDefault"))
        self.sendConfig.setText(_translate("MainWindow", "sendConfig"))
        self.sendData.setText(_translate("MainWindow", "sendData"))
        self.stopData.setText(_translate("MainWindow", "stopData"))
