# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWinUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1304, 881)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.FrftConfig = QtWidgets.QWidget(MainWindow)
        self.FrftConfig.setAutoFillBackground(False)
        self.FrftConfig.setStyleSheet("background-color: rgb(170, 170, 255)")
        self.FrftConfig.setObjectName("FrftConfig")
        self.tabWidget = QtWidgets.QTabWidget(self.FrftConfig)
        self.tabWidget.setGeometry(QtCore.QRect(80, 0, 1181, 751))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.TX_Config = QtWidgets.QWidget()
        self.TX_Config.setObjectName("TX_Config")
        self.papr_en_obj = QtWidgets.QCheckBox(self.TX_Config)
        self.papr_en_obj.setEnabled(True)
        self.papr_en_obj.setGeometry(QtCore.QRect(40, 30, 161, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.papr_en_obj.sizePolicy().hasHeightForWidth())
        self.papr_en_obj.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.papr_en_obj.setFont(font)
        self.papr_en_obj.setObjectName("papr_en_obj")
        self.depapr_thr_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.depapr_thr_obj.setGeometry(QtCore.QRect(40, 90, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.depapr_thr_obj.setFont(font)
        self.depapr_thr_obj.setSpecialValueText("")
        self.depapr_thr_obj.setMaximum(262143)
        self.depapr_thr_obj.setSingleStep(1)
        self.depapr_thr_obj.setProperty("value", 38050)
        self.depapr_thr_obj.setObjectName("depapr_thr_obj")
        self.depapr_thr_label = QtWidgets.QLabel(self.TX_Config)
        self.depapr_thr_label.setGeometry(QtCore.QRect(135, 85, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.depapr_thr_label.setFont(font)
        self.depapr_thr_label.setObjectName("depapr_thr_label")
        self.depapr_gain_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.depapr_gain_obj.setGeometry(QtCore.QRect(40, 490, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.depapr_gain_obj.setFont(font)
        self.depapr_gain_obj.setSpecialValueText("")
        self.depapr_gain_obj.setMaximum(65535)
        self.depapr_gain_obj.setSingleStep(1)
        self.depapr_gain_obj.setProperty("value", 16384)
        self.depapr_gain_obj.setObjectName("depapr_gain_obj")
        self.depapr_gain_label = QtWidgets.QLabel(self.TX_Config)
        self.depapr_gain_label.setGeometry(QtCore.QRect(135, 493, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.depapr_gain_label.setFont(font)
        self.depapr_gain_label.setObjectName("depapr_gain_label")
        self.MType_tx_obj = QtWidgets.QComboBox(self.TX_Config)
        self.MType_tx_obj.setGeometry(QtCore.QRect(40, 190, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MType_tx_obj.setFont(font)
        self.MType_tx_obj.setEditable(True)
        self.MType_tx_obj.setIconSize(QtCore.QSize(28, 28))
        self.MType_tx_obj.setObjectName("MType_tx_obj")
        self.MType_tx_obj.addItem("")
        self.MType_tx_obj.addItem("")
        self.MType_tx_obj.addItem("")
        self.MType_tx_obj.addItem("")
        self.MType_tx_label = QtWidgets.QLabel(self.TX_Config)
        self.MType_tx_label.setGeometry(QtCore.QRect(135, 182, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.MType_tx_label.setFont(font)
        self.MType_tx_label.setObjectName("MType_tx_label")
        self.car_num_tx_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.car_num_tx_obj.setGeometry(QtCore.QRect(40, 240, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.car_num_tx_obj.setFont(font)
        self.car_num_tx_obj.setSpecialValueText("")
        self.car_num_tx_obj.setMaximum(1048575)
        self.car_num_tx_obj.setSingleStep(1)
        self.car_num_tx_obj.setProperty("value", 1048575)
        self.car_num_tx_obj.setDisplayIntegerBase(16)
        self.car_num_tx_obj.setObjectName("car_num_tx_obj")
        self.car_num_tx_label = QtWidgets.QLabel(self.TX_Config)
        self.car_num_tx_label.setGeometry(QtCore.QRect(135, 234, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.car_num_tx_label.setFont(font)
        self.car_num_tx_label.setObjectName("car_num_tx_label")
        self.Alpha_tx_obj = QtWidgets.QDoubleSpinBox(self.TX_Config)
        self.Alpha_tx_obj.setGeometry(QtCore.QRect(40, 290, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Alpha_tx_obj.setFont(font)
        self.Alpha_tx_obj.setDecimals(1)
        self.Alpha_tx_obj.setMaximum(1.0)
        self.Alpha_tx_obj.setSingleStep(0.1)
        self.Alpha_tx_obj.setProperty("value", 0.5)
        self.Alpha_tx_obj.setObjectName("Alpha_tx_obj")
        self.Alpha_tx_label = QtWidgets.QLabel(self.TX_Config)
        self.Alpha_tx_label.setGeometry(QtCore.QRect(135, 282, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Alpha_tx_label.setFont(font)
        self.Alpha_tx_label.setObjectName("Alpha_tx_label")
        self.pilot_factor_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.pilot_factor_obj.setGeometry(QtCore.QRect(40, 340, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pilot_factor_obj.setFont(font)
        self.pilot_factor_obj.setSpecialValueText("")
        self.pilot_factor_obj.setMaximum(65535)
        self.pilot_factor_obj.setSingleStep(1)
        self.pilot_factor_obj.setProperty("value", 32767)
        self.pilot_factor_obj.setObjectName("pilot_factor_obj")
        self.pilot_factor_label = QtWidgets.QLabel(self.TX_Config)
        self.pilot_factor_label.setGeometry(QtCore.QRect(135, 334, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pilot_factor_label.setFont(font)
        self.pilot_factor_label.setObjectName("pilot_factor_label")
        self.pss_factor_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.pss_factor_obj.setGeometry(QtCore.QRect(40, 390, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pss_factor_obj.setFont(font)
        self.pss_factor_obj.setSpecialValueText("")
        self.pss_factor_obj.setMaximum(65535)
        self.pss_factor_obj.setSingleStep(1)
        self.pss_factor_obj.setProperty("value", 32767)
        self.pss_factor_obj.setObjectName("pss_factor_obj")
        self.pss_factor_label = QtWidgets.QLabel(self.TX_Config)
        self.pss_factor_label.setGeometry(QtCore.QRect(135, 384, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pss_factor_label.setFont(font)
        self.pss_factor_label.setObjectName("pss_factor_label")
        self.Sys_enble_obj = QtWidgets.QCheckBox(self.TX_Config)
        self.Sys_enble_obj.setEnabled(True)
        self.Sys_enble_obj.setGeometry(QtCore.QRect(500, 31, 151, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sys_enble_obj.sizePolicy().hasHeightForWidth())
        self.Sys_enble_obj.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Sys_enble_obj.setFont(font)
        self.Sys_enble_obj.setObjectName("Sys_enble_obj")
        self.Sys_reset_obj = QtWidgets.QCheckBox(self.TX_Config)
        self.Sys_reset_obj.setEnabled(True)
        self.Sys_reset_obj.setGeometry(QtCore.QRect(280, 31, 161, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sys_reset_obj.sizePolicy().hasHeightForWidth())
        self.Sys_reset_obj.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Sys_reset_obj.setFont(font)
        self.Sys_reset_obj.setObjectName("Sys_reset_obj")
        self.ModeBSorMS_label = QtWidgets.QLabel(self.TX_Config)
        self.ModeBSorMS_label.setGeometry(QtCore.QRect(135, 140, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ModeBSorMS_label.setFont(font)
        self.ModeBSorMS_label.setTextFormat(QtCore.Qt.PlainText)
        self.ModeBSorMS_label.setObjectName("ModeBSorMS_label")
        self.ModeBSorMS_obj = QtWidgets.QComboBox(self.TX_Config)
        self.ModeBSorMS_obj.setGeometry(QtCore.QRect(40, 140, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ModeBSorMS_obj.setFont(font)
        self.ModeBSorMS_obj.setEditable(True)
        self.ModeBSorMS_obj.setIconSize(QtCore.QSize(28, 28))
        self.ModeBSorMS_obj.setObjectName("ModeBSorMS_obj")
        self.ModeBSorMS_obj.addItem("")
        self.ModeBSorMS_obj.addItem("")
        self.ModeUDPorPN_label = QtWidgets.QLabel(self.TX_Config)
        self.ModeUDPorPN_label.setGeometry(QtCore.QRect(135, 540, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ModeUDPorPN_label.setFont(font)
        self.ModeUDPorPN_label.setTextFormat(QtCore.Qt.PlainText)
        self.ModeUDPorPN_label.setObjectName("ModeUDPorPN_label")
        self.ModeUDPorPN_obj = QtWidgets.QComboBox(self.TX_Config)
        self.ModeUDPorPN_obj.setGeometry(QtCore.QRect(40, 540, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ModeUDPorPN_obj.setFont(font)
        self.ModeUDPorPN_obj.setEditable(True)
        self.ModeUDPorPN_obj.setIconSize(QtCore.QSize(28, 28))
        self.ModeUDPorPN_obj.setObjectName("ModeUDPorPN_obj")
        self.ModeUDPorPN_obj.addItem("")
        self.ModeUDPorPN_obj.addItem("")
        self.Base_loop_en_label = QtWidgets.QLabel(self.TX_Config)
        self.Base_loop_en_label.setGeometry(QtCore.QRect(460, 140, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Base_loop_en_label.setFont(font)
        self.Base_loop_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.Base_loop_en_label.setObjectName("Base_loop_en_label")
        self.Base_loop_en_obj = QtWidgets.QComboBox(self.TX_Config)
        self.Base_loop_en_obj.setGeometry(QtCore.QRect(340, 140, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Base_loop_en_obj.setFont(font)
        self.Base_loop_en_obj.setEditable(True)
        self.Base_loop_en_obj.setIconSize(QtCore.QSize(28, 28))
        self.Base_loop_en_obj.setObjectName("Base_loop_en_obj")
        self.Base_loop_en_obj.addItem("")
        self.Base_loop_en_obj.addItem("")
        self.Rx_enb_label = QtWidgets.QLabel(self.TX_Config)
        self.Rx_enb_label.setGeometry(QtCore.QRect(430, 95, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Rx_enb_label.setFont(font)
        self.Rx_enb_label.setTextFormat(QtCore.Qt.PlainText)
        self.Rx_enb_label.setObjectName("Rx_enb_label")
        self.Rx_enb_obj = QtWidgets.QComboBox(self.TX_Config)
        self.Rx_enb_obj.setGeometry(QtCore.QRect(340, 90, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Rx_enb_obj.setFont(font)
        self.Rx_enb_obj.setEditable(True)
        self.Rx_enb_obj.setIconSize(QtCore.QSize(28, 28))
        self.Rx_enb_obj.setObjectName("Rx_enb_obj")
        self.Rx_enb_obj.addItem("")
        self.Rx_enb_obj.addItem("")
        self.Rx_channel_obj = QtWidgets.QComboBox(self.TX_Config)
        self.Rx_channel_obj.setGeometry(QtCore.QRect(700, 90, 111, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Rx_channel_obj.setFont(font)
        self.Rx_channel_obj.setEditable(True)
        self.Rx_channel_obj.setIconSize(QtCore.QSize(28, 28))
        self.Rx_channel_obj.setObjectName("Rx_channel_obj")
        self.Rx_channel_obj.addItem("")
        self.Rx_channel_obj.addItem("")
        self.Rx_channel_label = QtWidgets.QLabel(self.TX_Config)
        self.Rx_channel_label.setGeometry(QtCore.QRect(830, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Rx_channel_label.setFont(font)
        self.Rx_channel_label.setTextFormat(QtCore.Qt.PlainText)
        self.Rx_channel_label.setObjectName("Rx_channel_label")
        self.Rx_delay_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.Rx_delay_obj.setGeometry(QtCore.QRect(40, 440, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Rx_delay_obj.setFont(font)
        self.Rx_delay_obj.setSpecialValueText("")
        self.Rx_delay_obj.setMaximum(30)
        self.Rx_delay_obj.setSingleStep(1)
        self.Rx_delay_obj.setProperty("value", 20)
        self.Rx_delay_obj.setObjectName("Rx_delay_obj")
        self.Rx_delay_label = QtWidgets.QLabel(self.TX_Config)
        self.Rx_delay_label.setGeometry(QtCore.QRect(130, 430, 201, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Rx_delay_label.setFont(font)
        self.Rx_delay_label.setObjectName("Rx_delay_label")
        self.alway_tx_obj = QtWidgets.QComboBox(self.TX_Config)
        self.alway_tx_obj.setGeometry(QtCore.QRect(340, 390, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.alway_tx_obj.setFont(font)
        self.alway_tx_obj.setEditable(True)
        self.alway_tx_obj.setIconSize(QtCore.QSize(28, 28))
        self.alway_tx_obj.setObjectName("alway_tx_obj")
        self.alway_tx_obj.addItem("")
        self.alway_tx_obj.addItem("")
        self.alway_tx_label = QtWidgets.QLabel(self.TX_Config)
        self.alway_tx_label.setGeometry(QtCore.QRect(440, 390, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.alway_tx_label.setFont(font)
        self.alway_tx_label.setTextFormat(QtCore.Qt.PlainText)
        self.alway_tx_label.setObjectName("alway_tx_label")
        self.tx1_en_obj = QtWidgets.QComboBox(self.TX_Config)
        self.tx1_en_obj.setGeometry(QtCore.QRect(700, 140, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tx1_en_obj.setFont(font)
        self.tx1_en_obj.setEditable(True)
        self.tx1_en_obj.setIconSize(QtCore.QSize(28, 28))
        self.tx1_en_obj.setObjectName("tx1_en_obj")
        self.tx1_en_obj.addItem("")
        self.tx1_en_obj.addItem("")
        self.tx1_en_label = QtWidgets.QLabel(self.TX_Config)
        self.tx1_en_label.setGeometry(QtCore.QRect(820, 140, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tx1_en_label.setFont(font)
        self.tx1_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.tx1_en_label.setObjectName("tx1_en_label")
        self.tx2_en_obj = QtWidgets.QComboBox(self.TX_Config)
        self.tx2_en_obj.setGeometry(QtCore.QRect(690, 30, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tx2_en_obj.setFont(font)
        self.tx2_en_obj.setEditable(True)
        self.tx2_en_obj.setIconSize(QtCore.QSize(28, 28))
        self.tx2_en_obj.setObjectName("tx2_en_obj")
        self.tx2_en_obj.addItem("")
        self.tx2_en_obj.addItem("")
        self.tx2_en_label = QtWidgets.QLabel(self.TX_Config)
        self.tx2_en_label.setGeometry(QtCore.QRect(810, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tx2_en_label.setFont(font)
        self.tx2_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.tx2_en_label.setObjectName("tx2_en_label")
        self.rx1_en_obj = QtWidgets.QComboBox(self.TX_Config)
        self.rx1_en_obj.setGeometry(QtCore.QRect(700, 190, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rx1_en_obj.setFont(font)
        self.rx1_en_obj.setEditable(True)
        self.rx1_en_obj.setIconSize(QtCore.QSize(28, 28))
        self.rx1_en_obj.setObjectName("rx1_en_obj")
        self.rx1_en_obj.addItem("")
        self.rx1_en_obj.addItem("")
        self.rx1_en_label = QtWidgets.QLabel(self.TX_Config)
        self.rx1_en_label.setGeometry(QtCore.QRect(820, 190, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rx1_en_label.setFont(font)
        self.rx1_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.rx1_en_label.setObjectName("rx1_en_label")
        self.rx2_en_obj = QtWidgets.QComboBox(self.TX_Config)
        self.rx2_en_obj.setGeometry(QtCore.QRect(700, 240, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rx2_en_obj.setFont(font)
        self.rx2_en_obj.setEditable(True)
        self.rx2_en_obj.setIconSize(QtCore.QSize(28, 28))
        self.rx2_en_obj.setObjectName("rx2_en_obj")
        self.rx2_en_obj.addItem("")
        self.rx2_en_obj.addItem("")
        self.rx2_en_label = QtWidgets.QLabel(self.TX_Config)
        self.rx2_en_label.setGeometry(QtCore.QRect(820, 240, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rx2_en_label.setFont(font)
        self.rx2_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.rx2_en_label.setObjectName("rx2_en_label")
        self.TDD_EN_obj = QtWidgets.QComboBox(self.TX_Config)
        self.TDD_EN_obj.setGeometry(QtCore.QRect(340, 280, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TDD_EN_obj.setFont(font)
        self.TDD_EN_obj.setEditable(True)
        self.TDD_EN_obj.setIconSize(QtCore.QSize(28, 28))
        self.TDD_EN_obj.setObjectName("TDD_EN_obj")
        self.TDD_EN_obj.addItem("")
        self.TDD_EN_obj.addItem("")
        self.TDD_EN_label = QtWidgets.QLabel(self.TX_Config)
        self.TDD_EN_label.setGeometry(QtCore.QRect(430, 280, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TDD_EN_label.setFont(font)
        self.TDD_EN_label.setTextFormat(QtCore.Qt.PlainText)
        self.TDD_EN_label.setObjectName("TDD_EN_label")
        self.UDP_loop_label = QtWidgets.QLabel(self.TX_Config)
        self.UDP_loop_label.setGeometry(QtCore.QRect(430, 340, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UDP_loop_label.setFont(font)
        self.UDP_loop_label.setTextFormat(QtCore.Qt.PlainText)
        self.UDP_loop_label.setObjectName("UDP_loop_label")
        self.UDP_loop_obj = QtWidgets.QComboBox(self.TX_Config)
        self.UDP_loop_obj.setGeometry(QtCore.QRect(340, 340, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.UDP_loop_obj.setFont(font)
        self.UDP_loop_obj.setEditable(True)
        self.UDP_loop_obj.setIconSize(QtCore.QSize(28, 28))
        self.UDP_loop_obj.setObjectName("UDP_loop_obj")
        self.UDP_loop_obj.addItem("")
        self.UDP_loop_obj.addItem("")
        self.BBPort_obj = QtWidgets.QLineEdit(self.TX_Config)
        self.BBPort_obj.setGeometry(QtCore.QRect(320, 610, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BBPort_obj.setFont(font)
        self.BBPort_obj.setObjectName("BBPort_obj")
        self.BBIP_label = QtWidgets.QLabel(self.TX_Config)
        self.BBIP_label.setGeometry(QtCore.QRect(10, 620, 61, 18))
        self.BBIP_label.setTextFormat(QtCore.Qt.PlainText)
        self.BBIP_label.setObjectName("BBIP_label")
        self.BBIP_obj = QtWidgets.QLineEdit(self.TX_Config)
        self.BBIP_obj.setGeometry(QtCore.QRect(90, 610, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BBIP_obj.setFont(font)
        self.BBIP_obj.setObjectName("BBIP_obj")
        self.BBPort_label = QtWidgets.QLabel(self.TX_Config)
        self.BBPort_label.setGeometry(QtCore.QRect(230, 620, 81, 18))
        self.BBPort_label.setTextFormat(QtCore.Qt.PlainText)
        self.BBPort_label.setObjectName("BBPort_label")
        self.MType_rx_obj = QtWidgets.QComboBox(self.TX_Config)
        self.MType_rx_obj.setGeometry(QtCore.QRect(340, 180, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MType_rx_obj.setFont(font)
        self.MType_rx_obj.setEditable(True)
        self.MType_rx_obj.setIconSize(QtCore.QSize(28, 28))
        self.MType_rx_obj.setObjectName("MType_rx_obj")
        self.MType_rx_obj.addItem("")
        self.MType_rx_obj.addItem("")
        self.MType_rx_obj.addItem("")
        self.MType_rx_obj.addItem("")
        self.MType_rx_label = QtWidgets.QLabel(self.TX_Config)
        self.MType_rx_label.setGeometry(QtCore.QRect(440, 180, 191, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.MType_rx_label.setFont(font)
        self.MType_rx_label.setObjectName("MType_rx_label")
        self.car_num_rx_obj = QtWidgets.QSpinBox(self.TX_Config)
        self.car_num_rx_obj.setGeometry(QtCore.QRect(340, 230, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.car_num_rx_obj.setFont(font)
        self.car_num_rx_obj.setSpecialValueText("")
        self.car_num_rx_obj.setMaximum(1048575)
        self.car_num_rx_obj.setSingleStep(1)
        self.car_num_rx_obj.setProperty("value", 1048575)
        self.car_num_rx_obj.setDisplayIntegerBase(16)
        self.car_num_rx_obj.setObjectName("car_num_rx_obj")
        self.car_num_rx_label = QtWidgets.QLabel(self.TX_Config)
        self.car_num_rx_label.setGeometry(QtCore.QRect(440, 230, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.car_num_rx_label.setFont(font)
        self.car_num_rx_label.setObjectName("car_num_rx_label")
        self.tabWidget.addTab(self.TX_Config, "")
        self.RX_Config = QtWidgets.QWidget()
        self.RX_Config.setObjectName("RX_Config")
        self.agc_en_label = QtWidgets.QLabel(self.RX_Config)
        self.agc_en_label.setGeometry(QtCore.QRect(130, 38, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.agc_en_label.setFont(font)
        self.agc_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.agc_en_label.setObjectName("agc_en_label")
        self.agc_en_obj = QtWidgets.QComboBox(self.RX_Config)
        self.agc_en_obj.setGeometry(QtCore.QRect(20, 40, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.agc_en_obj.setFont(font)
        self.agc_en_obj.setEditable(True)
        self.agc_en_obj.setIconSize(QtCore.QSize(28, 28))
        self.agc_en_obj.setObjectName("agc_en_obj")
        self.agc_en_obj.addItem("")
        self.agc_en_obj.addItem("")
        self.frft_en_label = QtWidgets.QLabel(self.RX_Config)
        self.frft_en_label.setGeometry(QtCore.QRect(130, 84, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.frft_en_label.setFont(font)
        self.frft_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.frft_en_label.setObjectName("frft_en_label")
        self.frft_en_obj = QtWidgets.QComboBox(self.RX_Config)
        self.frft_en_obj.setGeometry(QtCore.QRect(20, 90, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frft_en_obj.setFont(font)
        self.frft_en_obj.setEditable(True)
        self.frft_en_obj.setIconSize(QtCore.QSize(28, 28))
        self.frft_en_obj.setObjectName("frft_en_obj")
        self.frft_en_obj.addItem("")
        self.frft_en_obj.addItem("")
        self.i_freq_est_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.i_freq_est_obj.setGeometry(QtCore.QRect(20, 190, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i_freq_est_obj.setFont(font)
        self.i_freq_est_obj.setMaximum(1000)
        self.i_freq_est_obj.setObjectName("i_freq_est_obj")
        self.i_freq_est_label = QtWidgets.QLabel(self.RX_Config)
        self.i_freq_est_label.setGeometry(QtCore.QRect(130, 195, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i_freq_est_label.setFont(font)
        self.i_freq_est_label.setObjectName("i_freq_est_label")
        self.sync_factor_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.sync_factor_obj.setGeometry(QtCore.QRect(20, 240, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sync_factor_obj.setFont(font)
        self.sync_factor_obj.setMaximum(65535)
        self.sync_factor_obj.setProperty("value", 20384)
        self.sync_factor_obj.setObjectName("sync_factor_obj")
        self.sync_factor_label = QtWidgets.QLabel(self.RX_Config)
        self.sync_factor_label.setGeometry(QtCore.QRect(130, 240, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sync_factor_label.setFont(font)
        self.sync_factor_label.setObjectName("sync_factor_label")
        self.equa_factor_label = QtWidgets.QLabel(self.RX_Config)
        self.equa_factor_label.setGeometry(QtCore.QRect(130, 290, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.equa_factor_label.setFont(font)
        self.equa_factor_label.setObjectName("equa_factor_label")
        self.equa_factor_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.equa_factor_obj.setGeometry(QtCore.QRect(20, 290, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.equa_factor_obj.setFont(font)
        self.equa_factor_obj.setMaximum(65535)
        self.equa_factor_obj.setProperty("value", 4022)
        self.equa_factor_obj.setObjectName("equa_factor_obj")
        self.Alpha_rx_obj = QtWidgets.QDoubleSpinBox(self.RX_Config)
        self.Alpha_rx_obj.setGeometry(QtCore.QRect(20, 350, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Alpha_rx_obj.setFont(font)
        self.Alpha_rx_obj.setDecimals(1)
        self.Alpha_rx_obj.setMaximum(1.0)
        self.Alpha_rx_obj.setSingleStep(0.1)
        self.Alpha_rx_obj.setProperty("value", 0.5)
        self.Alpha_rx_obj.setObjectName("Alpha_rx_obj")
        self.Alpha_rx_label = QtWidgets.QLabel(self.RX_Config)
        self.Alpha_rx_label.setGeometry(QtCore.QRect(130, 350, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Alpha_rx_label.setFont(font)
        self.Alpha_rx_label.setObjectName("Alpha_rx_label")
        self.equa_amp_en_label = QtWidgets.QLabel(self.RX_Config)
        self.equa_amp_en_label.setGeometry(QtCore.QRect(130, 468, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.equa_amp_en_label.setFont(font)
        self.equa_amp_en_label.setTextFormat(QtCore.Qt.PlainText)
        self.equa_amp_en_label.setObjectName("equa_amp_en_label")
        self.equa_amp_en_obj = QtWidgets.QComboBox(self.RX_Config)
        self.equa_amp_en_obj.setGeometry(QtCore.QRect(20, 470, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.equa_amp_en_obj.setFont(font)
        self.equa_amp_en_obj.setEditable(True)
        self.equa_amp_en_obj.setIconSize(QtCore.QSize(28, 28))
        self.equa_amp_en_obj.setObjectName("equa_amp_en_obj")
        self.equa_amp_en_obj.addItem("")
        self.equa_amp_en_obj.addItem("")
        self.car_thr1_label = QtWidgets.QLabel(self.RX_Config)
        self.car_thr1_label.setGeometry(QtCore.QRect(140, 520, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.car_thr1_label.setFont(font)
        self.car_thr1_label.setObjectName("car_thr1_label")
        self.car_thr1_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.car_thr1_obj.setGeometry(QtCore.QRect(20, 520, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.car_thr1_obj.setFont(font)
        self.car_thr1_obj.setMaximum(2147483647)
        self.car_thr1_obj.setProperty("value", 102656)
        self.car_thr1_obj.setDisplayIntegerBase(10)
        self.car_thr1_obj.setObjectName("car_thr1_obj")
        self.mmse_thr_label = QtWidgets.QLabel(self.RX_Config)
        self.mmse_thr_label.setGeometry(QtCore.QRect(140, 140, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.mmse_thr_label.setFont(font)
        self.mmse_thr_label.setObjectName("mmse_thr_label")
        self.mmse_thr_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.mmse_thr_obj.setGeometry(QtCore.QRect(20, 140, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mmse_thr_obj.setFont(font)
        self.mmse_thr_obj.setMaximum(2147483647)
        self.mmse_thr_obj.setProperty("value", 1000)
        self.mmse_thr_obj.setObjectName("mmse_thr_obj")
        self.car_thr3_label = QtWidgets.QLabel(self.RX_Config)
        self.car_thr3_label.setGeometry(QtCore.QRect(140, 620, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.car_thr3_label.setFont(font)
        self.car_thr3_label.setObjectName("car_thr3_label")
        self.car_thr3_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.car_thr3_obj.setGeometry(QtCore.QRect(20, 620, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.car_thr3_obj.setFont(font)
        self.car_thr3_obj.setMaximum(2147483647)
        self.car_thr3_obj.setProperty("value", 625000000)
        self.car_thr3_obj.setObjectName("car_thr3_obj")
        self.car_thr2_label = QtWidgets.QLabel(self.RX_Config)
        self.car_thr2_label.setGeometry(QtCore.QRect(140, 570, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.car_thr2_label.setFont(font)
        self.car_thr2_label.setObjectName("car_thr2_label")
        self.car_thr2_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.car_thr2_obj.setGeometry(QtCore.QRect(20, 570, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.car_thr2_obj.setFont(font)
        self.car_thr2_obj.setMaximum(2147483647)
        self.car_thr2_obj.setProperty("value", 6250000)
        self.car_thr2_obj.setObjectName("car_thr2_obj")
        self.equa_amp_label = QtWidgets.QLabel(self.RX_Config)
        self.equa_amp_label.setGeometry(QtCore.QRect(130, 407, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.equa_amp_label.setFont(font)
        self.equa_amp_label.setObjectName("equa_amp_label")
        self.equa_amp_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.equa_amp_obj.setGeometry(QtCore.QRect(20, 410, 99, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.equa_amp_obj.setFont(font)
        self.equa_amp_obj.setMaximum(65535)
        self.equa_amp_obj.setProperty("value", 16384)
        self.equa_amp_obj.setObjectName("equa_amp_obj")
        self.ms_T_sync2trig_label = QtWidgets.QLabel(self.RX_Config)
        self.ms_T_sync2trig_label.setGeometry(QtCore.QRect(540, 130, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ms_T_sync2trig_label.setFont(font)
        self.ms_T_sync2trig_label.setObjectName("ms_T_sync2trig_label")
        self.Time_tx_hold_label = QtWidgets.QLabel(self.RX_Config)
        self.Time_tx_hold_label.setGeometry(QtCore.QRect(540, 90, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Time_tx_hold_label.setFont(font)
        self.Time_tx_hold_label.setObjectName("Time_tx_hold_label")
        self.bs_tx_time_gap_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.bs_tx_time_gap_obj.setGeometry(QtCore.QRect(450, 240, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bs_tx_time_gap_obj.setFont(font)
        self.bs_tx_time_gap_obj.setSpecialValueText("")
        self.bs_tx_time_gap_obj.setMaximum(16777215)
        self.bs_tx_time_gap_obj.setSingleStep(1)
        self.bs_tx_time_gap_obj.setProperty("value", 50000)
        self.bs_tx_time_gap_obj.setObjectName("bs_tx_time_gap_obj")
        self.Time_tx_hold_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.Time_tx_hold_obj.setGeometry(QtCore.QRect(450, 90, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Time_tx_hold_obj.setFont(font)
        self.Time_tx_hold_obj.setSpecialValueText("")
        self.Time_tx_hold_obj.setMaximum(16777215)
        self.Time_tx_hold_obj.setSingleStep(1)
        self.Time_tx_hold_obj.setProperty("value", 34000)
        self.Time_tx_hold_obj.setObjectName("Time_tx_hold_obj")
        self.Trig_gap_cnt_label = QtWidgets.QLabel(self.RX_Config)
        self.Trig_gap_cnt_label.setGeometry(QtCore.QRect(540, 290, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Trig_gap_cnt_label.setFont(font)
        self.Trig_gap_cnt_label.setObjectName("Trig_gap_cnt_label")
        self.Trig_gap_cnt_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.Trig_gap_cnt_obj.setGeometry(QtCore.QRect(450, 290, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Trig_gap_cnt_obj.setFont(font)
        self.Trig_gap_cnt_obj.setSpecialValueText("")
        self.Trig_gap_cnt_obj.setMaximum(16777215)
        self.Trig_gap_cnt_obj.setSingleStep(1)
        self.Trig_gap_cnt_obj.setProperty("value", 100000)
        self.Trig_gap_cnt_obj.setObjectName("Trig_gap_cnt_obj")
        self.Time_trig2tx_label = QtWidgets.QLabel(self.RX_Config)
        self.Time_trig2tx_label.setGeometry(QtCore.QRect(540, 40, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Time_trig2tx_label.setFont(font)
        self.Time_trig2tx_label.setObjectName("Time_trig2tx_label")
        self.bs_tdd_time_gap_label = QtWidgets.QLabel(self.RX_Config)
        self.bs_tdd_time_gap_label.setGeometry(QtCore.QRect(540, 180, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bs_tdd_time_gap_label.setFont(font)
        self.bs_tdd_time_gap_label.setObjectName("bs_tdd_time_gap_label")
        self.Time_trig2tx_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.Time_trig2tx_obj.setGeometry(QtCore.QRect(450, 40, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Time_trig2tx_obj.setFont(font)
        self.Time_trig2tx_obj.setSpecialValueText("")
        self.Time_trig2tx_obj.setMaximum(16777215)
        self.Time_trig2tx_obj.setSingleStep(1)
        self.Time_trig2tx_obj.setProperty("value", 34000)
        self.Time_trig2tx_obj.setObjectName("Time_trig2tx_obj")
        self.ms_T_sync2trig_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.ms_T_sync2trig_obj.setGeometry(QtCore.QRect(450, 140, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ms_T_sync2trig_obj.setFont(font)
        self.ms_T_sync2trig_obj.setSpecialValueText("")
        self.ms_T_sync2trig_obj.setMaximum(16777215)
        self.ms_T_sync2trig_obj.setSingleStep(1)
        self.ms_T_sync2trig_obj.setProperty("value", 21880)
        self.ms_T_sync2trig_obj.setObjectName("ms_T_sync2trig_obj")
        self.bs_tdd_time_gap_obj = QtWidgets.QSpinBox(self.RX_Config)
        self.bs_tdd_time_gap_obj.setGeometry(QtCore.QRect(450, 190, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bs_tdd_time_gap_obj.setFont(font)
        self.bs_tdd_time_gap_obj.setSpecialValueText("")
        self.bs_tdd_time_gap_obj.setMaximum(16777215)
        self.bs_tdd_time_gap_obj.setSingleStep(1)
        self.bs_tdd_time_gap_obj.setProperty("value", 100000)
        self.bs_tdd_time_gap_obj.setObjectName("bs_tdd_time_gap_obj")
        self.bs_tx_time_gap_label = QtWidgets.QLabel(self.RX_Config)
        self.bs_tx_time_gap_label.setGeometry(QtCore.QRect(540, 240, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bs_tx_time_gap_label.setFont(font)
        self.bs_tx_time_gap_label.setObjectName("bs_tx_time_gap_label")
        self.tabWidget.addTab(self.RX_Config, "")
        self.RF_Config = QtWidgets.QWidget()
        self.RF_Config.setObjectName("RF_Config")
        self.Amplifier_label = QtWidgets.QLabel(self.RF_Config)
        self.Amplifier_label.setGeometry(QtCore.QRect(130, 30, 81, 18))
        self.Amplifier_label.setTextFormat(QtCore.Qt.PlainText)
        self.Amplifier_label.setObjectName("Amplifier_label")
        self.Amplifier_obj = QtWidgets.QComboBox(self.RF_Config)
        self.Amplifier_obj.setGeometry(QtCore.QRect(20, 30, 99, 24))
        self.Amplifier_obj.setEditable(True)
        self.Amplifier_obj.setObjectName("Amplifier_obj")
        self.Amplifier_obj.addItem("")
        self.Amplifier_obj.addItem("")
        self.filter3_3p5G_obj = QtWidgets.QComboBox(self.RF_Config)
        self.filter3_3p5G_obj.setGeometry(QtCore.QRect(20, 80, 99, 24))
        self.filter3_3p5G_obj.setEditable(True)
        self.filter3_3p5G_obj.setObjectName("filter3_3p5G_obj")
        self.filter3_3p5G_obj.addItem("")
        self.filter3_3p5G_obj.addItem("")
        self.filter3_3p5G_label = QtWidgets.QLabel(self.RF_Config)
        self.filter3_3p5G_label.setGeometry(QtCore.QRect(130, 80, 121, 18))
        self.filter3_3p5G_label.setTextFormat(QtCore.Qt.PlainText)
        self.filter3_3p5G_label.setObjectName("filter3_3p5G_label")
        self.filter3p5_4G_obj = QtWidgets.QComboBox(self.RF_Config)
        self.filter3p5_4G_obj.setGeometry(QtCore.QRect(20, 130, 99, 24))
        self.filter3p5_4G_obj.setEditable(True)
        self.filter3p5_4G_obj.setObjectName("filter3p5_4G_obj")
        self.filter3p5_4G_obj.addItem("")
        self.filter3p5_4G_obj.addItem("")
        self.filter3p5_4G_label = QtWidgets.QLabel(self.RF_Config)
        self.filter3p5_4G_label.setGeometry(QtCore.QRect(130, 130, 111, 18))
        self.filter3p5_4G_label.setTextFormat(QtCore.Qt.PlainText)
        self.filter3p5_4G_label.setObjectName("filter3p5_4G_label")
        self.filter4p5_5G_obj = QtWidgets.QComboBox(self.RF_Config)
        self.filter4p5_5G_obj.setGeometry(QtCore.QRect(20, 180, 99, 24))
        self.filter4p5_5G_obj.setEditable(True)
        self.filter4p5_5G_obj.setObjectName("filter4p5_5G_obj")
        self.filter4p5_5G_obj.addItem("")
        self.filter4p5_5G_obj.addItem("")
        self.filter4p5_5G_label = QtWidgets.QLabel(self.RF_Config)
        self.filter4p5_5G_label.setGeometry(QtCore.QRect(130, 180, 111, 18))
        self.filter4p5_5G_label.setTextFormat(QtCore.Qt.PlainText)
        self.filter4p5_5G_label.setObjectName("filter4p5_5G_label")
        self.filter5_5p5G_obj = QtWidgets.QComboBox(self.RF_Config)
        self.filter5_5p5G_obj.setGeometry(QtCore.QRect(20, 230, 99, 24))
        self.filter5_5p5G_obj.setEditable(True)
        self.filter5_5p5G_obj.setObjectName("filter5_5p5G_obj")
        self.filter5_5p5G_obj.addItem("")
        self.filter5_5p5G_obj.addItem("")
        self.filter5_5p5G_label = QtWidgets.QLabel(self.RF_Config)
        self.filter5_5p5G_label.setGeometry(QtCore.QRect(130, 230, 111, 18))
        self.filter5_5p5G_label.setTextFormat(QtCore.Qt.PlainText)
        self.filter5_5p5G_label.setObjectName("filter5_5p5G_label")
        self.RFIP_obj = QtWidgets.QLineEdit(self.RF_Config)
        self.RFIP_obj.setGeometry(QtCore.QRect(60, 610, 121, 41))
        self.RFIP_obj.setObjectName("RFIP_obj")
        self.RFIP_label = QtWidgets.QLabel(self.RF_Config)
        self.RFIP_label.setGeometry(QtCore.QRect(10, 620, 41, 18))
        self.RFIP_label.setTextFormat(QtCore.Qt.PlainText)
        self.RFIP_label.setObjectName("RFIP_label")
        self.RFPort_label = QtWidgets.QLabel(self.RF_Config)
        self.RFPort_label.setGeometry(QtCore.QRect(230, 620, 61, 18))
        self.RFPort_label.setTextFormat(QtCore.Qt.PlainText)
        self.RFPort_label.setObjectName("RFPort_label")
        self.RFPort_obj = QtWidgets.QLineEdit(self.RF_Config)
        self.RFPort_obj.setGeometry(QtCore.QRect(290, 610, 71, 41))
        self.RFPort_obj.setObjectName("RFPort_obj")
        self.tabWidget.addTab(self.RF_Config, "")
        self.statistical = QtWidgets.QWidget()
        self.statistical.setObjectName("statistical")
        self.start = QtWidgets.QPushButton(self.statistical)
        self.start.setGeometry(QtCore.QRect(290, 540, 112, 34))
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.statistical)
        self.stop.setGeometry(QtCore.QRect(420, 540, 112, 34))
        self.stop.setObjectName("stop")
        self.noise_pwr_sum_label = QtWidgets.QLabel(self.statistical)
        self.noise_pwr_sum_label.setGeometry(QtCore.QRect(550, 73, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.noise_pwr_sum_label.setFont(font)
        self.noise_pwr_sum_label.setObjectName("noise_pwr_sum_label")
        self.noise_pwr_sum_show = QtWidgets.QLabel(self.statistical)
        self.noise_pwr_sum_show.setGeometry(QtCore.QRect(730, 83, 91, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.noise_pwr_sum_show.setFont(font)
        self.noise_pwr_sum_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noise_pwr_sum_show.setText("")
        self.noise_pwr_sum_show.setObjectName("noise_pwr_sum_show")
        self.singal_pwr_sum_show = QtWidgets.QLabel(self.statistical)
        self.singal_pwr_sum_show.setGeometry(QtCore.QRect(730, 43, 91, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.singal_pwr_sum_show.setFont(font)
        self.singal_pwr_sum_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.singal_pwr_sum_show.setText("")
        self.singal_pwr_sum_show.setObjectName("singal_pwr_sum_show")
        self.singal_pwr_sum_label = QtWidgets.QLabel(self.statistical)
        self.singal_pwr_sum_label.setGeometry(QtCore.QRect(550, 33, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.singal_pwr_sum_label.setFont(font)
        self.singal_pwr_sum_label.setObjectName("singal_pwr_sum_label")
        self.SNR_show = QtWidgets.QLabel(self.statistical)
        self.SNR_show.setGeometry(QtCore.QRect(340, 160, 480, 100))
        self.SNR_show.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.SNR_show.setText("")
        self.SNR_show.setObjectName("SNR_show")
        self.layoutWidget = QtWidgets.QWidget(self.statistical)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 51, 291, 448))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.errbit_show = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.errbit_show.setFont(font)
        self.errbit_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.errbit_show.setText("")
        self.errbit_show.setTextFormat(QtCore.Qt.AutoText)
        self.errbit_show.setObjectName("errbit_show")
        self.gridLayout.addWidget(self.errbit_show, 0, 1, 1, 1)
        self.tolfrm_show = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tolfrm_show.setFont(font)
        self.tolfrm_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tolfrm_show.setText("")
        self.tolfrm_show.setObjectName("tolfrm_show")
        self.gridLayout.addWidget(self.tolfrm_show, 1, 1, 1, 1)
        self.o_freq_est_t_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.o_freq_est_t_label.setFont(font)
        self.o_freq_est_t_label.setObjectName("o_freq_est_t_label")
        self.gridLayout.addWidget(self.o_freq_est_t_label, 8, 0, 1, 2)
        self.hard_decision_err_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.hard_decision_err_label.setFont(font)
        self.hard_decision_err_label.setObjectName("hard_decision_err_label")
        self.gridLayout.addWidget(self.hard_decision_err_label, 4, 0, 1, 2)
        self.hard_decision_err_show = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.hard_decision_err_show.setFont(font)
        self.hard_decision_err_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.hard_decision_err_show.setText("")
        self.hard_decision_err_show.setObjectName("hard_decision_err_show")
        self.gridLayout.addWidget(self.hard_decision_err_show, 5, 1, 1, 1)
        self.crc_error_show = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.crc_error_show.setFont(font)
        self.crc_error_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.crc_error_show.setText("")
        self.crc_error_show.setObjectName("crc_error_show")
        self.gridLayout.addWidget(self.crc_error_show, 11, 1, 1, 1)
        self.errbit_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.errbit_label.setFont(font)
        self.errbit_label.setObjectName("errbit_label")
        self.gridLayout.addWidget(self.errbit_label, 0, 0, 1, 1)
        self.tolfrm_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.tolfrm_label.setFont(font)
        self.tolfrm_label.setObjectName("tolfrm_label")
        self.gridLayout.addWidget(self.tolfrm_label, 1, 0, 1, 1)
        self.o_freq_est_r_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.o_freq_est_r_label.setFont(font)
        self.o_freq_est_r_label.setObjectName("o_freq_est_r_label")
        self.gridLayout.addWidget(self.o_freq_est_r_label, 6, 0, 1, 2)
        self.o_freq_est_r_show = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.o_freq_est_r_show.setFont(font)
        self.o_freq_est_r_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.o_freq_est_r_show.setText("")
        self.o_freq_est_r_show.setObjectName("o_freq_est_r_show")
        self.gridLayout.addWidget(self.o_freq_est_r_show, 7, 1, 1, 1)
        self.o_freq_est_t_show = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.o_freq_est_t_show.setFont(font)
        self.o_freq_est_t_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.o_freq_est_t_show.setText("")
        self.o_freq_est_t_show.setObjectName("o_freq_est_t_show")
        self.gridLayout.addWidget(self.o_freq_est_t_show, 9, 1, 1, 1)
        self.crc_error_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.crc_error_label.setFont(font)
        self.crc_error_label.setObjectName("crc_error_label")
        self.gridLayout.addWidget(self.crc_error_label, 10, 0, 1, 2)
        self.error_dft_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.error_dft_label.setFont(font)
        self.error_dft_label.setObjectName("error_dft_label")
        self.gridLayout.addWidget(self.error_dft_label, 2, 0, 1, 2)
        self.error_dft_show = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.error_dft_show.setFont(font)
        self.error_dft_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.error_dft_show.setText("")
        self.error_dft_show.setObjectName("error_dft_show")
        self.gridLayout.addWidget(self.error_dft_show, 3, 1, 1, 1)
        self.statisticalPort_label = QtWidgets.QLabel(self.statistical)
        self.statisticalPort_label.setGeometry(QtCore.QRect(10, 540, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.statisticalPort_label.setFont(font)
        self.statisticalPort_label.setTextFormat(QtCore.Qt.PlainText)
        self.statisticalPort_label.setObjectName("statisticalPort_label")
        self.statisticalPort_obj = QtWidgets.QLineEdit(self.statistical)
        self.statisticalPort_obj.setGeometry(QtCore.QRect(190, 540, 71, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statisticalPort_obj.setFont(font)
        self.statisticalPort_obj.setObjectName("statisticalPort_obj")
        self.SNR_current_label = QtWidgets.QLabel(self.statistical)
        self.SNR_current_label.setGeometry(QtCore.QRect(530, 123, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.SNR_current_label.setFont(font)
        self.SNR_current_label.setObjectName("SNR_current_label")
        self.SNR_current_show = QtWidgets.QLabel(self.statistical)
        self.SNR_current_show.setGeometry(QtCore.QRect(730, 120, 91, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.SNR_current_show.setFont(font)
        self.SNR_current_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SNR_current_show.setText("")
        self.SNR_current_show.setObjectName("SNR_current_show")
        self.constellation_show = QtWidgets.QLabel(self.statistical)
        self.constellation_show.setGeometry(QtCore.QRect(340, 290, 200, 200))
        self.constellation_show.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.constellation_show.setText("")
        self.constellation_show.setObjectName("constellation_show")
        self.tabWidget.addTab(self.statistical, "")
        self.others = QtWidgets.QWidget()
        self.others.setObjectName("others")
        self.groupBox = QtWidgets.QGroupBox(self.others)
        self.groupBox.setGeometry(QtCore.QRect(60, 120, 651, 551))
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 30, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(170, 30, 54, 12))
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(320, 30, 71, 20))
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(240, 30, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(400, 30, 54, 12))
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 70, 71, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(170, 70, 54, 12))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(243, 62, 71, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(400, 70, 54, 12))
        self.label_11.setObjectName("label_11")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(80, 150, 71, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 150, 61, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(160, 150, 54, 12))
        self.label_13.setObjectName("label_13")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setGeometry(QtCore.QRect(310, 150, 71, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(390, 150, 54, 12))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(233, 150, 61, 20))
        self.label_15.setObjectName("label_15")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(80, 190, 71, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(160, 190, 54, 12))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(10, 190, 71, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(310, 190, 71, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(390, 190, 54, 12))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(233, 182, 61, 20))
        self.label_19.setObjectName("label_19")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_10.setGeometry(QtCore.QRect(90, 260, 71, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(170, 260, 54, 12))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(10, 260, 81, 21))
        self.label_21.setObjectName("label_21")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_11.setGeometry(QtCore.QRect(320, 260, 71, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(400, 260, 54, 12))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(233, 252, 81, 20))
        self.label_23.setObjectName("label_23")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_12.setGeometry(QtCore.QRect(90, 300, 71, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(170, 300, 54, 12))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(10, 300, 81, 16))
        self.label_25.setObjectName("label_25")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(100, 480, 74, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setGeometry(QtCore.QRect(20, 480, 81, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setGeometry(QtCore.QRect(240, 480, 101, 16))
        self.label_27.setObjectName("label_27")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(340, 480, 71, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 110, 141, 21))
        self.checkBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 230, 151, 21))
        self.checkBox_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 350, 151, 21))
        self.checkBox_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 380, 151, 21))
        self.checkBox_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setGeometry(QtCore.QRect(230, 350, 151, 21))
        self.checkBox_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_8.setGeometry(QtCore.QRect(230, 380, 151, 21))
        self.checkBox_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_9.setGeometry(QtCore.QRect(210, 410, 171, 21))
        self.checkBox_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_10.setGeometry(QtCore.QRect(10, 410, 151, 21))
        self.checkBox_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_10.setObjectName("checkBox_10")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 480, 75, 23))
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(320, 70, 74, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_3 = QtWidgets.QLabel(self.others)
        self.label_3.setGeometry(QtCore.QRect(550, 30, 81, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.others)
        self.comboBox.setGeometry(QtCore.QRect(460, 30, 74, 22))
        self.comboBox.setObjectName("comboBox")
        self.lineEdit = QtWidgets.QLineEdit(self.others)
        self.lineEdit.setGeometry(QtCore.QRect(140, 30, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.others)
        self.label_2.setGeometry(QtCore.QRect(380, 30, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.others)
        self.label.setGeometry(QtCore.QRect(63, 30, 71, 20))
        self.label.setObjectName("label")
        self.comboBox_2 = QtWidgets.QComboBox(self.others)
        self.comboBox_2.setGeometry(QtCore.QRect(650, 30, 74, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.others)
        self.groupBox_2.setGeometry(QtCore.QRect(740, 520, 311, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 291, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_13.setEnabled(False)
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout.addWidget(self.lineEdit_13)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout.addWidget(self.lineEdit_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.others)
        self.lineEdit_14.setGeometry(QtCore.QRect(140, 60, 113, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_28 = QtWidgets.QLabel(self.others)
        self.label_28.setGeometry(QtCore.QRect(60, 60, 81, 20))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.others)
        self.label_29.setGeometry(QtCore.QRect(260, 30, 16, 20))
        self.label_29.setObjectName("label_29")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.others)
        self.lineEdit_15.setGeometry(QtCore.QRect(280, 30, 61, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.pushButton_4 = QtWidgets.QPushButton(self.others)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 60, 81, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.checkBox_11 = QtWidgets.QCheckBox(self.others)
        self.checkBox_11.setGeometry(QtCore.QRect(380, 60, 201, 20))
        self.checkBox_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_11.setObjectName("checkBox_11")
        self.pushButton = QtWidgets.QPushButton(self.others)
        self.pushButton.setGeometry(QtCore.QRect(740, 650, 81, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.others)
        self.pushButton_5.setGeometry(QtCore.QRect(650, 60, 81, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.others)
        self.groupBox_3.setGeometry(QtCore.QRect(730, 120, 311, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.textBrowser_recv = QtWidgets.QTextBrowser(self.others)
        self.textBrowser_recv.setGeometry(QtCore.QRect(750, 280, 256, 192))
        self.textBrowser_recv.setObjectName("textBrowser_recv")
        self.tabWidget.addTab(self.others, "")
        self.setDefault = QtWidgets.QPushButton(self.FrftConfig)
        self.setDefault.setGeometry(QtCore.QRect(60, 770, 112, 34))
        self.setDefault.setObjectName("setDefault")
        self.sendConfig = QtWidgets.QPushButton(self.FrftConfig)
        self.sendConfig.setGeometry(QtCore.QRect(220, 770, 112, 34))
        self.sendConfig.setObjectName("sendConfig")
        self.sendData = QtWidgets.QPushButton(self.FrftConfig)
        self.sendData.setGeometry(QtCore.QRect(380, 770, 112, 34))
        self.sendData.setObjectName("sendData")
        self.stopData = QtWidgets.QPushButton(self.FrftConfig)
        self.stopData.setGeometry(QtCore.QRect(540, 770, 112, 34))
        self.stopData.setObjectName("stopData")
        MainWindow.setCentralWidget(self.FrftConfig)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1304, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.MType_tx_obj.setCurrentIndex(0)
        self.ModeBSorMS_obj.setCurrentIndex(0)
        self.ModeUDPorPN_obj.setCurrentIndex(0)
        self.Base_loop_en_obj.setCurrentIndex(0)
        self.Rx_enb_obj.setCurrentIndex(0)
        self.Rx_channel_obj.setCurrentIndex(0)
        self.alway_tx_obj.setCurrentIndex(0)
        self.tx1_en_obj.setCurrentIndex(0)
        self.tx2_en_obj.setCurrentIndex(0)
        self.rx1_en_obj.setCurrentIndex(0)
        self.rx2_en_obj.setCurrentIndex(0)
        self.TDD_EN_obj.setCurrentIndex(0)
        self.UDP_loop_obj.setCurrentIndex(0)
        self.MType_rx_obj.setCurrentIndex(0)
        self.agc_en_obj.setCurrentIndex(0)
        self.frft_en_obj.setCurrentIndex(0)
        self.equa_amp_en_obj.setCurrentIndex(1)
        self.Amplifier_obj.setCurrentIndex(0)
        self.filter3_3p5G_obj.setCurrentIndex(0)
        self.filter3p5_4G_obj.setCurrentIndex(0)
        self.filter4p5_5G_obj.setCurrentIndex(0)
        self.filter5_5p5G_obj.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.papr_en_obj.setText(_translate("MainWindow", "Papr使能"))
        self.depapr_thr_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.depapr_thr_label.setText(_translate("MainWindow", "Papr门限"))
        self.depapr_gain_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.depapr_gain_label.setText(_translate("MainWindow", "Papr幅度系数"))
        self.MType_tx_obj.setCurrentText(_translate("MainWindow", "QPSK"))
        self.MType_tx_obj.setItemText(0, _translate("MainWindow", "QPSK"))
        self.MType_tx_obj.setItemText(1, _translate("MainWindow", "16QAM"))
        self.MType_tx_obj.setItemText(2, _translate("MainWindow", "64QAM"))
        self.MType_tx_obj.setItemText(3, _translate("MainWindow", "256QAM"))
        self.MType_tx_label.setText(_translate("MainWindow", "发端调试方式"))
        self.car_num_tx_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.car_num_tx_label.setText(_translate("MainWindow", "子载波控制"))
        self.Alpha_tx_label.setText(_translate("MainWindow", "frft加权系数"))
        self.pilot_factor_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.pilot_factor_label.setText(_translate("MainWindow", "导频幅度"))
        self.pss_factor_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.pss_factor_label.setText(_translate("MainWindow", "前导幅度"))
        self.Sys_enble_obj.setText(_translate("MainWindow", "系统使能"))
        self.Sys_reset_obj.setText(_translate("MainWindow", "系统复位"))
        self.ModeBSorMS_label.setText(_translate("MainWindow", "BS/MS"))
        self.ModeBSorMS_obj.setCurrentText(_translate("MainWindow", "MS"))
        self.ModeBSorMS_obj.setItemText(0, _translate("MainWindow", "MS"))
        self.ModeBSorMS_obj.setItemText(1, _translate("MainWindow", "BS"))
        self.ModeUDPorPN_label.setText(_translate("MainWindow", "数据源"))
        self.ModeUDPorPN_obj.setCurrentText(_translate("MainWindow", "UDP"))
        self.ModeUDPorPN_obj.setItemText(0, _translate("MainWindow", "UDP"))
        self.ModeUDPorPN_obj.setItemText(1, _translate("MainWindow", "PN"))
        self.Base_loop_en_label.setText(_translate("MainWindow", "基带打环使能"))
        self.Base_loop_en_obj.setCurrentText(_translate("MainWindow", "outterLoop"))
        self.Base_loop_en_obj.setItemText(0, _translate("MainWindow", "outterLoop"))
        self.Base_loop_en_obj.setItemText(1, _translate("MainWindow", "innerLoop"))
        self.Rx_enb_label.setText(_translate("MainWindow", "接收使能"))
        self.Rx_enb_obj.setCurrentText(_translate("MainWindow", "normal"))
        self.Rx_enb_obj.setItemText(0, _translate("MainWindow", "normal"))
        self.Rx_enb_obj.setItemText(1, _translate("MainWindow", "debug"))
        self.Rx_channel_obj.setCurrentText(_translate("MainWindow", "channel 0"))
        self.Rx_channel_obj.setItemText(0, _translate("MainWindow", "channel 0"))
        self.Rx_channel_obj.setItemText(1, _translate("MainWindow", "channel 1"))
        self.Rx_channel_label.setText(_translate("MainWindow", "接收频道"))
        self.Rx_delay_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.Rx_delay_label.setText(_translate("MainWindow", "同步后数据延时"))
        self.alway_tx_obj.setCurrentText(_translate("MainWindow", "TXandRX"))
        self.alway_tx_obj.setItemText(0, _translate("MainWindow", "TXandRX"))
        self.alway_tx_obj.setItemText(1, _translate("MainWindow", "onlyTX"))
        self.alway_tx_label.setText(_translate("MainWindow", "常发使能"))
        self.tx1_en_obj.setCurrentText(_translate("MainWindow", "close"))
        self.tx1_en_obj.setItemText(0, _translate("MainWindow", "close"))
        self.tx1_en_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.tx1_en_label.setText(_translate("MainWindow", "TX1使能"))
        self.tx2_en_obj.setCurrentText(_translate("MainWindow", "close"))
        self.tx2_en_obj.setItemText(0, _translate("MainWindow", "close"))
        self.tx2_en_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.tx2_en_label.setText(_translate("MainWindow", "FIFO复位"))
        self.rx1_en_obj.setCurrentText(_translate("MainWindow", "close"))
        self.rx1_en_obj.setItemText(0, _translate("MainWindow", "close"))
        self.rx1_en_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.rx1_en_label.setText(_translate("MainWindow", "RX1使能"))
        self.rx2_en_obj.setCurrentText(_translate("MainWindow", "close"))
        self.rx2_en_obj.setItemText(0, _translate("MainWindow", "close"))
        self.rx2_en_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.rx2_en_label.setText(_translate("MainWindow", "RX2使能"))
        self.TDD_EN_obj.setCurrentText(_translate("MainWindow", "close"))
        self.TDD_EN_obj.setItemText(0, _translate("MainWindow", "close"))
        self.TDD_EN_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.TDD_EN_label.setText(_translate("MainWindow", "TDD模式"))
        self.UDP_loop_label.setText(_translate("MainWindow", "UDP环路使能"))
        self.UDP_loop_obj.setCurrentText(_translate("MainWindow", "close"))
        self.UDP_loop_obj.setItemText(0, _translate("MainWindow", "close"))
        self.UDP_loop_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.BBPort_obj.setText(_translate("MainWindow", "8000"))
        self.BBIP_label.setText(_translate("MainWindow", "基带IP"))
        self.BBIP_obj.setText(_translate("MainWindow", "192.168.1.84"))
        self.BBPort_label.setText(_translate("MainWindow", "基带Port"))
        self.MType_rx_obj.setCurrentText(_translate("MainWindow", "QPSK"))
        self.MType_rx_obj.setItemText(0, _translate("MainWindow", "QPSK"))
        self.MType_rx_obj.setItemText(1, _translate("MainWindow", "16QAM"))
        self.MType_rx_obj.setItemText(2, _translate("MainWindow", "64QAM"))
        self.MType_rx_obj.setItemText(3, _translate("MainWindow", "256QAM"))
        self.MType_rx_label.setText(_translate("MainWindow", "接收调试方式"))
        self.car_num_rx_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.car_num_rx_label.setText(_translate("MainWindow", "收端子载波控制"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TX_Config), _translate("MainWindow", "TXRX_Config"))
        self.agc_en_label.setText(_translate("MainWindow", "数字AGC使能"))
        self.agc_en_obj.setCurrentText(_translate("MainWindow", "close"))
        self.agc_en_obj.setItemText(0, _translate("MainWindow", "close"))
        self.agc_en_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.frft_en_label.setText(_translate("MainWindow", "Frft使能"))
        self.frft_en_obj.setCurrentText(_translate("MainWindow", "close"))
        self.frft_en_obj.setItemText(0, _translate("MainWindow", "close"))
        self.frft_en_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.i_freq_est_obj.setSuffix(_translate("MainWindow", "Hz"))
        self.i_freq_est_label.setText(_translate("MainWindow", "频偏设置"))
        self.sync_factor_label.setText(_translate("MainWindow", "同步系数"))
        self.equa_factor_label.setText(_translate("MainWindow", "均衡系数"))
        self.Alpha_rx_label.setText(_translate("MainWindow", "收端FRFT加权系数"))
        self.equa_amp_en_label.setText(_translate("MainWindow", "幅度调整使能"))
        self.equa_amp_en_obj.setCurrentText(_translate("MainWindow", "enable"))
        self.equa_amp_en_obj.setItemText(0, _translate("MainWindow", "close"))
        self.equa_amp_en_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.car_thr1_label.setText(_translate("MainWindow", "干扰检测门限一"))
        self.mmse_thr_label.setText(_translate("MainWindow", "MMSE均衡门限"))
        self.car_thr3_label.setText(_translate("MainWindow", "干扰检测门限三"))
        self.car_thr2_label.setText(_translate("MainWindow", "干扰检测门限二"))
        self.equa_amp_label.setText(_translate("MainWindow", "幅度调整"))
        self.ms_T_sync2trig_label.setText(_translate("MainWindow", "ms_T_sync2trig"))
        self.Time_tx_hold_label.setText(_translate("MainWindow", "Time_tx_hold"))
        self.bs_tx_time_gap_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.Time_tx_hold_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.Trig_gap_cnt_label.setText(_translate("MainWindow", "Trig_gap_cnt"))
        self.Trig_gap_cnt_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.Time_trig2tx_label.setText(_translate("MainWindow", "Time_trig2tx"))
        self.bs_tdd_time_gap_label.setText(_translate("MainWindow", "bs_tdd_time_gap"))
        self.Time_trig2tx_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.ms_T_sync2trig_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.bs_tdd_time_gap_obj.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'等线\'; font-size:10.5pt;\">depapr_thr</span></p></body></html>"))
        self.bs_tx_time_gap_label.setText(_translate("MainWindow", "bs_tx_time_gap"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RX_Config), _translate("MainWindow", "System_Config"))
        self.Amplifier_label.setText(_translate("MainWindow", "Amplifier"))
        self.Amplifier_obj.setCurrentText(_translate("MainWindow", "close"))
        self.Amplifier_obj.setItemText(0, _translate("MainWindow", "close"))
        self.Amplifier_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.filter3_3p5G_obj.setCurrentText(_translate("MainWindow", "close"))
        self.filter3_3p5G_obj.setItemText(0, _translate("MainWindow", "close"))
        self.filter3_3p5G_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.filter3_3p5G_label.setText(_translate("MainWindow", "filter3_3p5G"))
        self.filter3p5_4G_obj.setCurrentText(_translate("MainWindow", "close"))
        self.filter3p5_4G_obj.setItemText(0, _translate("MainWindow", "close"))
        self.filter3p5_4G_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.filter3p5_4G_label.setText(_translate("MainWindow", "filter3p5_4G"))
        self.filter4p5_5G_obj.setCurrentText(_translate("MainWindow", "close"))
        self.filter4p5_5G_obj.setItemText(0, _translate("MainWindow", "close"))
        self.filter4p5_5G_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.filter4p5_5G_label.setText(_translate("MainWindow", "filter4p5_5G"))
        self.filter5_5p5G_obj.setCurrentText(_translate("MainWindow", "close"))
        self.filter5_5p5G_obj.setItemText(0, _translate("MainWindow", "close"))
        self.filter5_5p5G_obj.setItemText(1, _translate("MainWindow", "enable"))
        self.filter5_5p5G_label.setText(_translate("MainWindow", "filter5_5p5G"))
        self.RFIP_obj.setText(_translate("MainWindow", "192.168.1.38"))
        self.RFIP_label.setText(_translate("MainWindow", "RFIP"))
        self.RFPort_label.setText(_translate("MainWindow", "RFPort"))
        self.RFPort_obj.setText(_translate("MainWindow", "6005"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RF_Config), _translate("MainWindow", "RF_Config"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.noise_pwr_sum_label.setText(_translate("MainWindow", "noise_pwr_sum"))
        self.singal_pwr_sum_label.setText(_translate("MainWindow", "singal_pwr_sum"))
        self.o_freq_est_t_label.setText(_translate("MainWindow", "o_freq_est_t"))
        self.hard_decision_err_label.setText(_translate("MainWindow", "FIFOEmpty"))
        self.errbit_label.setText(_translate("MainWindow", "errbit"))
        self.tolfrm_label.setText(_translate("MainWindow", "tolfrm"))
        self.o_freq_est_r_label.setText(_translate("MainWindow", "o_freq_est_r"))
        self.crc_error_label.setText(_translate("MainWindow", "crc_error"))
        self.error_dft_label.setText(_translate("MainWindow", "error_dft"))
        self.statisticalPort_label.setText(_translate("MainWindow", "接收统计数据端口"))
        self.statisticalPort_obj.setText(_translate("MainWindow", "7000"))
        self.SNR_current_label.setText(_translate("MainWindow", "SNR_current"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statistical), _translate("MainWindow", "Statistical"))
        self.groupBox.setTitle(_translate("MainWindow", "FMC205参数配置"))
        self.label_4.setText(_translate("MainWindow", "接收频点:"))
        self.label_5.setText(_translate("MainWindow", "GHz"))
        self.label_6.setText(_translate("MainWindow", "发射频点:"))
        self.label_7.setText(_translate("MainWindow", "GHz"))
        self.label_8.setText(_translate("MainWindow", "侦测频点:"))
        self.label_9.setText(_translate("MainWindow", "GHz"))
        self.label_10.setText(_translate("MainWindow", "观察通道:"))
        self.label_11.setText(_translate("MainWindow", "GHz"))
        self.label_12.setText(_translate("MainWindow", "RX1增益:"))
        self.label_13.setText(_translate("MainWindow", "dB"))
        self.label_14.setText(_translate("MainWindow", "dB"))
        self.label_15.setText(_translate("MainWindow", "TX1衰减:"))
        self.label_16.setText(_translate("MainWindow", "dB"))
        self.label_17.setText(_translate("MainWindow", "RX2增益:"))
        self.label_18.setText(_translate("MainWindow", "dB"))
        self.label_19.setText(_translate("MainWindow", "RX2衰减："))
        self.label_20.setText(_translate("MainWindow", "dB"))
        self.label_21.setText(_translate("MainWindow", "ORX1增益："))
        self.label_22.setText(_translate("MainWindow", "dB"))
        self.label_23.setText(_translate("MainWindow", "SNRX增益："))
        self.label_24.setText(_translate("MainWindow", "dB"))
        self.label_25.setText(_translate("MainWindow", "ORX2增益："))
        self.label_26.setText(_translate("MainWindow", "时钟选择："))
        self.label_27.setText(_translate("MainWindow", "校准选择："))
        self.checkBox.setText(_translate("MainWindow", "常开"))
        self.checkBox_2.setText(_translate("MainWindow", "AGC使能：   "))
        self.checkBox_4.setText(_translate("MainWindow", "ORXAGC使能： "))
        self.checkBox_5.setText(_translate("MainWindow", "RX1使能：    "))
        self.checkBox_6.setText(_translate("MainWindow", "RX2使能：    "))
        self.checkBox_7.setText(_translate("MainWindow", "TX1使能：    "))
        self.checkBox_8.setText(_translate("MainWindow", "TX2使能：    "))
        self.checkBox_9.setText(_translate("MainWindow", "TX外供本振：   "))
        self.checkBox_10.setText(_translate("MainWindow", "RX外供本振： "))
        self.pushButton_2.setText(_translate("MainWindow", "单次校准"))
        self.label_3.setText(_translate("MainWindow", "配置模式:"))
        self.label_2.setText(_translate("MainWindow", "FPGA选择:"))
        self.label.setText(_translate("MainWindow", "板卡IP:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "硬件参考信息"))
        self.pushButton_3.setText(_translate("MainWindow", "点我读取信息"))
        self.label_28.setText(_translate("MainWindow", "控制端IP:"))
        self.label_29.setText(_translate("MainWindow", ":"))
        self.pushButton_4.setText(_translate("MainWindow", "转发"))
        self.checkBox_11.setText(_translate("MainWindow", "收中间件数据校验： "))
        self.pushButton.setText(_translate("MainWindow", "退出"))
        self.pushButton_5.setText(_translate("MainWindow", "清空数据"))
        self.groupBox_3.setTitle(_translate("MainWindow", "收发数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.others), _translate("MainWindow", "FMC205"))
        self.setDefault.setText(_translate("MainWindow", "发送默认配置"))
        self.sendConfig.setText(_translate("MainWindow", "发送当前配置"))
        self.sendData.setText(_translate("MainWindow", "发送数据"))
        self.stopData.setText(_translate("MainWindow", "停止发送数据"))
